// Generated by Suite Builder from a crawl of the site. The "forgot_password" form on ForgotPasswordPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what ForgotPasswordTasks.fillForgotPasswordForm takes.
package com.herokuapp.theinternet.tests.pages.forgotpassword;

import com.herokuapp.theinternet.tests.core.SiteConfig;

/**
 * The "forgot_password" form on ForgotPasswordPage, as one value: its fields in page order, what
 * {@link ForgotPasswordTasks#fillForgotPasswordForm(ForgotPassword)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code ForgotPassword.sample().withEMail("...")}.
 */
public record ForgotPassword(String eMail) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DeMail=...) or in suite.properties, by its name.
     */
    public static ForgotPassword sample() {
        return new ForgotPassword(
                SiteConfig.value("eMail", "test@example.com"));
    }

    /** This ForgotPassword with eMail in place of its own. */
    public ForgotPassword withEMail(String eMail) {
        return new ForgotPassword(eMail);
    }
}
