// Generated by Suite Builder from a crawl of the site. Site navigation: the header and footer links.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.header.actions;

import com.herokuapp.theinternet.tests.core.PageElement;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.pages.footer.FooterElements;
import com.herokuapp.theinternet.tests.pages.header.HeaderElements;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Navigation through the site's header and footer, from any page: {@code somePage.navigateTo()}.
 * Each method opens the link's dropdown when it is in one (hovering first; clicking when hovering
 * does not open it and what opens it is not a link), clicks the link, moves the mouse out of the way
 * so the menu closes, and waits until the page it leads to has fully loaded.
 */
public class HeaderNavigableActions {
    private final Page page;

    public HeaderNavigableActions(Page page) {
        this.page = page;
    }

    // Header

    // Footer

    // ==== YOURS (navigation): safe to edit; regenerating keeps what is between these lines ====
    // More ways around the site (a search box in the header, a language switch), e.g.:
    // public SearchResultsPage search(String words) {
    //     UserActions.type(page, HeaderElements.SEARCH_INPUT, words);
    //     UserActions.pressKey(page, HeaderElements.SEARCH_INPUT, "Enter");
    //     return new SearchResultsPage(page).get();
    // }
    // ==== END YOURS (navigation) ====

    /**
     * What opens a dropdown, or part of one: hovered, and clicked too when hovering doesn't open it.
     * {@code clickToOpen} is false for a real link (a link to "#" is a button dressed as a link):
     * one is clicked with its navigation held back, so the page stays where it is.
     */
    private record Opener(PageElement element, boolean clickToOpen) {
    }

    /** Holds back the next click's navigation on a link, and lets it go again (see clickHeldBack). */
    private static final String HOLD_NAVIGATION = "a => { a.__suiteHold = (e) => e.preventDefault(); a.addEventListener('click', a.__suiteHold, true); }";
    private static final String RELEASE_NAVIGATION = "a => { if (a.__suiteHold) a.removeEventListener('click', a.__suiteHold, true); delete a.__suiteHold; }";

    /**
     * Opens the link's dropdown, and then each part of it the link is in (a mega menu's category,
     * say: Services, then Data & AI), clicks the link, and moves the mouse away so the menu closes.
     */
    private void click(PageElement link, Opener... openers) {
        for (int i = 0; i < openers.length; i++) {
            open(openers[i], i + 1 < openers.length ? openers[i + 1].element() : link);
        }
        UserActions.clickOn(link.locator(page), link.label());
        page.mouse().move(0, 0);
    }

    /**
     * Hovers the opener (clicks it too, if hovering isn't enough) until what it opens shows: the next
     * opener, or the link. A menu whose script starts after the page has loaded
     * ignores a hover made before it: the item lights up, nothing opens, and a mouse that stays put
     * never tries again. So the mouse moves away and comes back. If it never shows, the click after
     * this says what was missing.
     */
    private void open(Opener opener, PageElement shows) {
        if (shows.locator(page).isVisible()) return; // open already (the category a mega menu shows first)
        long end = System.currentTimeMillis() + WaitActions.ELEMENT_TIMEOUT;
        while (true) {
            opener.element().locator(page).hover();
            if (WaitActions.waitForVisibilityOf(page, shows, 1_500)) return;
            if (opener.clickToOpen()) opener.element().locator(page).click();
            else clickHeldBack(opener.element().locator(page));
            if (WaitActions.waitForVisibilityOf(page, shows, 1_500)) return;
            if (System.currentTimeMillis() > end) return;
            page.mouse().move(0, 0);
        }
    }

    /**
     * Clicks a link that opens a dropdown, with its navigation held back: a menu whose script opens
     * on a click (and keeps the page) opens; a plain link does nothing, and the page stays. The hold
     * goes as soon as the click is made, so a later click on the link follows it.
     */
    private static void clickHeldBack(com.microsoft.playwright.Locator link) {
        try {
            link.evaluate(HOLD_NAVIGATION);
            link.click();
        } catch (com.microsoft.playwright.PlaywrightException e) {
            // covered, or redrawn: hovered again
        } finally {
            try {
                link.evaluate(RELEASE_NAVIGATION);
            } catch (com.microsoft.playwright.PlaywrightException e) {
                // gone with the menu's redraw: nothing to let go
            }
        }
    }

    /**
     * For pages the crawl did not read: the URL and the page load. {@code from} is the address before
     * the click (null when there was none), to tell a click that went nowhere from a link that leads
     * somewhere else.
     */
    private static void arrive(Page tab, String path, String from) {
        if (!WaitActions.waitForUrl(tab, path)) {
            String now = tab.url();
            if (now.equals(from)) {
                throw new AssertionError("The click did not leave the page: still on " + now
                        + " (a script may handle this link, e.g. by opening a sign-in window)");
            }
            throw new AssertionError("The link to " + path + " led to " + now
                    + " instead (the link points to an old or moved address, or the site sends it elsewhere)");
        }
        // On its address: the page is there. A late load event is a slow part of the page, named, not a failure.
        if (!WaitActions.waitForPageLoad(tab)) {
            WaitActions.noteStillLoading(tab, path);
        }
    }
}
