// Generated by Suite Builder from a crawl of the site. Click actions for IframePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.iframe.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.iframe.IframeElements;
import com.herokuapp.theinternet.tests.pages.iframe.IframePage;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on IframePage. Clicks that change page return the next page; others return this. */
public class IframeClickActions {
    private final Page page;

    public IframeClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the menuitem "File". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage file() {
        UserActions.click(page, IframeElements.FILE_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the menuitem "Edit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage edit() {
        UserActions.click(page, IframeElements.EDIT_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the menuitem "View". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage view() {
        UserActions.click(page, IframeElements.VIEW_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the menuitem "Format". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage format() {
        UserActions.click(page, IframeElements.FORMAT_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Undo". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage undo() {
        UserActions.click(page, IframeElements.UNDO_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Redo". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage redo() {
        UserActions.click(page, IframeElements.REDO_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Formats". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage formats() {
        UserActions.click(page, IframeElements.FORMATS_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Bold". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage bold() {
        UserActions.click(page, IframeElements.BOLD_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Italic". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage italic() {
        UserActions.click(page, IframeElements.ITALIC_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Align left". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage alignLeft() {
        UserActions.click(page, IframeElements.ALIGN_LEFT_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Align center". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage alignCenter() {
        UserActions.click(page, IframeElements.ALIGN_CENTER_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Align right". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage alignRight() {
        UserActions.click(page, IframeElements.ALIGN_RIGHT_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Justify". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage justify() {
        UserActions.click(page, IframeElements.JUSTIFY_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Decrease indent". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage decreaseIndent() {
        UserActions.click(page, IframeElements.DECREASE_INDENT_BUTTON);
        return new IframePage(page);
    }

    /** Clicks the button "Increase indent". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IframePage increaseIndent() {
        UserActions.click(page, IframeElements.INCREASE_INDENT_BUTTON);
        return new IframePage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public IframeVerifyActions verify() {
        return new IframeVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public IframeClickActions acceptTerms() {
    //     UserActions.click(page, IframeElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
