// Generated by Suite Builder from a crawl of the site. Click actions for DynamicControlsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamiccontrols.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.dynamiccontrols.DynamicControlsElements;
import com.herokuapp.theinternet.tests.pages.dynamiccontrols.DynamicControlsPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on DynamicControlsPage. Clicks that change page return the next page; others return this. */
public class DynamicControlsClickActions {
    private final WebDriver driver;

    public DynamicControlsClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks the button "Remove". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public DynamicControlsPage remove() {
        UserActions.click(driver, DynamicControlsElements.REMOVE_BUTTON);
        return new DynamicControlsPage(driver);
    }

    /** Clicks the button "Enable". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public DynamicControlsPage enable() {
        UserActions.click(driver, DynamicControlsElements.ENABLE_BUTTON);
        return new DynamicControlsPage(driver);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public DynamicControlsVerifyActions verify() {
        return new DynamicControlsVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public DynamicControlsClickActions acceptTerms() {
    //     UserActions.click(driver, DynamicControlsElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
