// Generated by Suite Builder from a crawl of the site. CheckActions for DynamicControlsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamiccontrols.actions;

import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.dynamiccontrols.DynamicControlsElements;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Checkboxes and radio buttons on DynamicControlsPage: page.check() checks them, page.uncheck() unchecks them.
 * The crawl's own are below; add more (elements to DynamicControlsElements, then methods here) in the YOURS block.
 */
public class DynamicControlsCheckActions {
    private final WebDriver driver;
    private final boolean check;

    public DynamicControlsCheckActions(WebDriver driver, boolean check) {
        this.driver = driver;
        this.check = check;
    }

    /** Ticks the checkbox "CHECKBOX" (page.check()), or unticks it (page.uncheck()). */
    public DynamicControlsCheckActions checkbox() {
        UserActions.setTicked(driver, DynamicControlsElements.CHECKBOX, check);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public DynamicControlsVerifyActions verify() {
        return new DynamicControlsVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per checkbox or radio button, e.g.:
    // public DynamicControlsCheckActions terms() {
    //     UserActions.setTicked(driver, DynamicControlsElements.TERMS_CHECKBOX, check);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
