// Generated by Suite Builder from a crawl of the site. Which requests are ads.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
/**
 * Ad networks, blocked in every test (the support file) unless run with --expose blockAds=false. Their
 * full-page ads take over the click a test makes (automationexercise.com: a click on "Products"
 * landed on /#google_vignette), and they keep pages loading. They are not the site under test.
 */
export const Ads = {
  /** Hosts of ad networks; their subdomains count too. */
  HOSTS: [
    'doubleclick.net', 'googlesyndication.com', 'googleadservices.com', 'adservice.google.com',
    'googletagservices.com', 'amazon-adsystem.com', 'adnxs.com', 'taboola.com',
    'outbrain.com', 'criteo.com', 'pubmatic.com', 'rubiconproject.com',
    'moatads.com', 'casalemedia.com', 'smartadserver.com', 'yieldmo.com',
    'sharethrough.com',
    // ==== YOURS (more-hosts): safe to edit; regenerating keeps what is between these lines ====
    // More hosts to block on this site (an ad or tracking network the list above lacks), e.g.:
    // 'ads.example.net',
    // ==== END YOURS (more-hosts) ====
  ],

  /**
   * Answers every request to an ad network with nothing: one intercept, a pattern for every host and
   * its subdomains. (Cypress takes a hostname as a pattern only as a RegExp: "*.doubleclick.net" as a
   * string is refused as not a host name.)
   */
  block(): void {
    cy.intercept({ hostname: Ads.pattern() }, { statusCode: 204, body: '', log: false });
  },

  /** doubleclick.net, ads.doubleclick.net, ...: every host, and its subdomains, and nothing else. */
  pattern(): RegExp {
    const hosts = Ads.HOSTS.map((h) => h.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
    return new RegExp(`(^|\\.)(${hosts.join('|')})$`, 'i');
  },
};
