// Generated by Suite Builder from a crawl of the site. Finds the element a visitor sees: the first visible match, by XPath or CSS.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import type { Locator, PageElement } from './PageElement';
import { shared } from './Shared';

/**
 * Finding elements the way a visitor sees them: the first visible match. Sites repeat links in hover
 * menus, mobile menus and hidden tabs, and a hidden copy found first can't be clicked. XPath works
 * as well as CSS: Cypress has no XPath of its own, so this adds one query, cy.visibleElement(),
 * retried like cy.get() until what follows it passes or the command timeout runs out.
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      /** The first visible match of a page element (empty while there is none); retried for timeout ms if given. */
      visibleElement(element: PageElement, options?: { timeout?: number }): Chainable<JQuery<HTMLElement>>;
      /** Every match of a page element, visible or not. */
      allElements(element: PageElement): Chainable<JQuery<HTMLElement>>;
    }
  }
}

/** Every match of the element in a document, visible or not. */
export function matchesOf(page: Document, element: Locator): HTMLElement[] {
  // Inside a frame, through each frame element of its path (same-site frames only); none while one is missing.
  let doc: Document | null | undefined = page;
  for (const frame of element.frame ?? []) doc = (doc?.evaluate(frame, doc, null, 9, null).singleNodeValue as HTMLIFrameElement | null)?.contentDocument;
  if (!doc) return [];
  // A locator that is not valid is said as one, not as "not shown" (Cypress still retries it to its timeout).
  const invalid = (e: unknown) => new Error(`The locator ${'css' in element ? element.css : element.xpath} is not valid: ${String(e instanceof Error ? e.message : e).split('\n')[0]}`);
  if ('css' in element) {
    try {
      return Array.from(doc.querySelectorAll<HTMLElement>(element.css));
    } catch (e) {
      throw invalid(e);
    }
  }
  let found: XPathResult;
  try {
    found = doc.evaluate(element.xpath, doc, null, 7 /* ORDERED_NODE_SNAPSHOT_TYPE */, null);
  } catch (e) {
    throw invalid(e);
  }
  const out: HTMLElement[] = [];
  for (let i = 0; i < found.snapshotLength; i++) out.push(found.snapshotItem(i) as HTMLElement);
  return out;
}

/**
 * The element's first visible match in the page, as jQuery (empty while there is none). Code that
 * must see "not shown" reads through this, from cy.document(): after cy.visibleElement(), an empty
 * match fails the command with Cypress's own "Expected to find element" before the code sees it.
 * `reveal`, for a check that expects it shown: when it is in the page but not shown, its first match
 * is scrolled to the middle of the window, as a visitor scrolls to it, so a section that fades in as
 * it is scrolled to (opacity 0 until then, which Cypress counts as hidden) shows by the next look
 * (Site G, 2026-10-03).
 */
export function shownIn(doc: Document, element: Locator, reveal = false): JQuery<HTMLElement> {
  const all = matchesOf(doc, element);
  const first = all.find((e) => Cypress.dom.isVisible(e));
  if (!first && reveal && all.length) all[0].scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' });
  return Cypress.$(first ? [first] : []);
}

/** What a visitor reads in it: its innerText (runs of spaces and line breaks as the page shows them), trimmed. */
export function textOf($found: JQuery<HTMLElement>): string {
  return $found.length ? ($found[0].innerText ?? $found.text()).trim() : '';
}

/** The page under test's document (not the spec's). */
export function pageDocument(): Document | undefined {
  return (cy as unknown as { state(key: string): Document | undefined }).state('document');
}

// Registered once per test window: the support file and every spec bundle this module, and Cypress
// refuses a query registered twice ("visibleElement is an existing Cypress command or query").
const queries = shared('queries', () => ({ added: false }));
if (!queries.added) {
  queries.added = true;
  Cypress.Commands.addQuery('visibleElement', function (element: PageElement, options?: { timeout?: number }) {
    // As cy.get() does with its own timeout option.
    if (options?.timeout !== undefined) (this as unknown as { set(key: string, value: unknown): void }).set('timeout', options.timeout);
    return () => {
      const doc = pageDocument();
      const first = doc ? matchesOf(doc, element).find((e) => Cypress.dom.isVisible(e)) : undefined;
      return Cypress.$(first ? [first] : []);
    };
  });

  Cypress.Commands.addQuery('allElements', function (element: PageElement) {
    return () => {
      const doc = pageDocument();
      return Cypress.$(doc ? matchesOf(doc, element) : []);
    };
  });
}

export const Find = {
  /** The element, once it is visible; fails naming it after the command timeout. */
  visible(element: PageElement): Cypress.Chainable<JQuery<HTMLElement>> {
    // Waited for through the document, so the failure says which element, in words.
    cy.document({ log: false }).should((doc) => {
      if (!shownIn(doc, element, true).length) throw new Error(`${element.label} was not shown within ${Cypress.config('defaultCommandTimeout') / 1000} s: it is not on the page, or only where a visitor cannot see it (a closed menu, another slide, a layout for another screen size)`);
    });
    return cy.visibleElement(element);
  },

  /** True now (no waiting) when the element is visible: for choices a step makes, not for checks. */
  isVisibleNow(element: PageElement): boolean {
    const doc = pageDocument();
    return !!doc && matchesOf(doc, element).some((e) => Cypress.dom.isVisible(e));
  },
};

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (extras) ====
