// Generated by Suite Builder from a crawl of the site. How a page element is written: its locator and its label.
// EDIT RULES: do not edit this file; regenerating replaces all of it. Elements live in each page's Elements file.
/** How an element is found: XPath, or a CSS selector. */
/** How to find an element; `frame`, for one inside a frame, is its frame path. */
export type Locator = ({ readonly xpath: string } | { readonly css: string }) & { readonly frame?: readonly string[] };

/** An element of a page: how to find it, and how steps and failures name it. */
export type PageElement = Locator & {
  /** The constant's name, e.g. SUBMIT_BUTTON. */
  readonly name: string;
  /** How steps and failure messages name it: SUBMIT_BUTTON is "the submit button". */
  readonly label: string;
};

export function byXPath(xpath: string): Locator {
  return { xpath };
}

export function byCss(css: string): Locator {
  return { css };
}

/** "SUBMIT_BUTTON" -> "the submit button"; "YOUR_CV_INPUT" -> "your cv input", never "the your cv input". */
export function labelOf(name: string): string {
  const words = name.toLowerCase().split('_').join(' ');
  return words.startsWith('your ') ? words : `the ${words}`;
}

/**
 * A page's elements, each named after its key: elements({ SUBMIT_BUTTON: byCss('#submit') }).
 * A key can say its label better: { SEND_BUTTON: { ...byCss('#send'), label: 'the Send button' } }.
 */
export function elements<T extends Record<string, Locator & { label?: string }>>(locators: T): { readonly [K in keyof T]: PageElement } {
  const out: Record<string, PageElement> = {};
  for (const [name, locator] of Object.entries(locators)) out[name] = { ...locator, name, label: locator.label ?? labelOf(name) };
  return out as { readonly [K in keyof T]: PageElement };
}

/** One element made on the fly (a link to one page of a family). */
export function element(name: string, locator: Locator, label = labelOf(name)): PageElement {
  return { ...locator, name, label };
}

/** A header or footer element: where its link leads (null for what opens a dropdown). */
export type NavElement = PageElement & { readonly path: string | null };

/** The header's or footer's elements, each named after its key: navElements({ ABOUT_LINK: { path: '/about', ...byXPath('...') } }). */
export function navElements<T extends Record<string, Locator & { path: string | null; label?: string }>>(locators: T): { readonly [K in keyof T]: NavElement } {
  const out: Record<string, NavElement> = {};
  for (const [name, locator] of Object.entries(locators)) out[name] = { ...locator, name, label: locator.label ?? labelOf(name) };
  return out as { readonly [K in keyof T]: NavElement };
}
