// Generated by Suite Builder from a crawl of the site. Signs in as a role before a test of a page read signed in.
// EDIT RULES: do not edit this file; regenerating replaces all of it. Each role's sign-in page is in cypress/support/pages/signin/SignIns.ts.
import { shownIn } from './Find';
import { StepLog } from './StepLog';
import { UserActions } from './UserActions';
import { SIGN_INS } from '../pages/signin/SignIns';

/**
 * Signs in as the role before a test of a page the crawl read signed in as it (G-158, G-159): its account
 * from the config's Node side (the environment, Suite Builder's store when docked, secrets/<role>.login),
 * typed through the role's sign-in page (pages/signin/SignIns.ts) as secrets, never in the log. Once a run
 * per role: cy.session keeps the session for every spec after.
 */
export function signInAs(role: string): void {
  const form = SIGN_INS[role];
  if (!form) throw new Error(`No sign-in form was found for ${role} when the site was crawled: add it to cypress/support/pages/signin/SignIns.ts, or crawl again with suite crawl --login.`);
  StepLog.step(`Sign in as ${role} at ${form.path}`);
  cy.session(
    role,
    () => {
      cy.task('account', role, { log: false }).then((found) => {
        const account = found as { username: string; password: string; from: string; missing?: string };
        if (account.missing) throw new Error(account.missing);
        StepLog.note(`the account in ${account.from}`);
        cy.visit(form.path, { log: false });
        if (form.username) UserActions.typeSecret(form.username, account.username);
        UserActions.typeSecret(form.password, account.password);
        if (form.submit) UserActions.click(form.submit);
        else UserActions.pressKey(form.password, 'Enter');
        // The page the sign-in leads to, loaded, its form gone (a form shown again is a wrong account). Not
        // just the form gone: while the old page unloads it is gone too, before the site's answer, which
        // carries the session's cookie, arrives, and cy.session would keep a session without it (Ghost's
        // the-internet run, 2026-10-04: /secure then sent the test back to /login).
        StepLog.step(`Check that the sign-in at ${form.path} led to a page without its form`);
        cy.document({ log: false, timeout: Cypress.config('pageLoadTimeout') }).should((doc) => {
          if (doc.location.href === 'about:blank' || doc.readyState !== 'complete' || !doc.body) throw new Error(`The page after signing in at ${form.path} had not loaded`);
          if (shownIn(doc, form.password).length) throw new Error(`Could not sign in as ${role} at ${form.path}: the sign-in form was shown again (is ${account.from} right?)`);
        });
      });
    },
    { cacheAcrossSpecs: true },
  );
}
