// Generated by Suite Builder from a crawl of the site. What a visitor does, one step at a time.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { CookieBanner } from './CookieBanner';
import { Find, shownIn, textOf } from './Find';
import type { PageElement } from './PageElement';
import { StepLog } from './StepLog';

/**
 * The library of things a visitor does. Each one logs its step in plain English (StepLog), then does
 * it to the first visible match once it is visible and ready (Cypress waits for that itself, up to
 * the command timeout). Page actions are built from these, one line each:
 *
 *   email(text: string): HomeEnterActions {
 *     UserActions.type(HomeElements.EMAIL_INPUT, text);
 *     return this;
 *   }
 *
 * Steps name elements by their label: EMAIL_INPUT is "the email input".
 */
export const UserActions = {
  /** Clicks it. */
  click(element: PageElement): void {
    StepLog.step(`Click ${element.label}`);
    CookieBanner.acceptLate();
    Find.visible(element).click();
  },

  /**
   * Clicks a link that opens a new tab. Cypress drives one tab, so the link opens in this one
   * instead (its target is taken off first); the next page object carries on here.
   */
  clickOpeningNewTab(element: PageElement): void {
    StepLog.step(`Click ${element.label} (opens a new tab: followed in this one)`);
    CookieBanner.acceptLate();
    Find.visible(element).invoke('removeAttr', 'target').click();
  },

  /**
   * Points the mouse at it: the events a menu's script listens for. A menu that opens on CSS
   * :hover alone does not open (Cypress can't move a real mouse); click what is in it with
   * clickHidden(), as the header's navigation does.
   */
  hover(element: PageElement): void {
    StepLog.step(`Point at ${element.label}`);
    Find.visible(element).trigger('mouseover').trigger('mouseenter');
  },

  /** Clicks a link a visitor reaches through a menu that only opens on CSS :hover. */
  clickHidden(element: PageElement): void {
    StepLog.step(`Click ${element.label} (in a menu that opens on hover)`);
    CookieBanner.acceptLate();
    cy.document({ log: false }).then((doc) => {
      const $shown = shownIn(doc, element);
      if ($shown.length) return cy.wrap($shown, { log: false }).click();
      return cy.allElements(element).first().click({ force: true });
    });
  },

  /** Replaces what is in the field with this text. */
  type(element: PageElement, text: string): void {
    StepLog.step(`Type "${text}" into ${element.label}`);
    Find.visible(element).clear().type(text, { parseSpecialCharSequences: false });
  },

  /** Types a password or other secret. The step says a secret was typed, never what it was. */
  typeSecret(element: PageElement, secret: string): void {
    StepLog.step(`Type the secret into ${element.label}`);
    Find.visible(element).clear().type(secret, { parseSpecialCharSequences: false, log: false });
  },

  /** Empties the field. */
  clear(element: PageElement): void {
    StepLog.step(`Clear ${element.label}`);
    Find.visible(element).clear();
  },

  /** Chooses an option of a dropdown (a select element) by its value or its visible text. */
  choose(element: PageElement, option: string): void {
    StepLog.step(`Choose "${option}" in ${element.label}`);
    Find.visible(element).select(option);
  },

  /** Attaches a file to a file field (input type="file"), by its path from the suite's folder; a file field is never typed into. */
  attach(element: PageElement, path: string): void {
    StepLog.step(`Attach ${path} to ${element.label}`);
    Find.visible(element).selectFile(path);
  },

  /** Ticks a checkbox or picks a radio button. */
  tick(element: PageElement): void {
    UserActions.setTicked(element, true);
  },

  /** Unticks a checkbox. */
  untick(element: PageElement): void {
    UserActions.setTicked(element, false);
  },

  /** Ticks or unticks: what a page's check() and uncheck() actions call. */
  setTicked(element: PageElement, ticked: boolean): void {
    StepLog.step(`${ticked ? 'Tick' : 'Untick'} ${element.label}`);
    if (ticked) Find.visible(element).check();
    else Find.visible(element).uncheck();
  },

  /** Presses a key in it: "Enter", "Escape", "ArrowDown" (Cypress has no Tab key). */
  pressKey(element: PageElement, key: string): void {
    StepLog.step(`Press ${key} in ${element.label}`);
    Find.visible(element).type(KEYS[key.toLowerCase()] ?? key);
  },

  /** Reads the text a visitor sees in it, trimmed. The step says what it read. */
  readText(element: PageElement): Cypress.Chainable<string> {
    return Find.visible(element).then(($e) => {
      const text = textOf($e);
      StepLog.step(`Read ${element.label}: "${text}"`);
      return cy.wrap(text, { log: false });
    });
  },

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // More things a visitor does on this site (drag a slider, upload a file), each logging its step.
  // ==== END YOURS (extras) ====
};

/** Key names as browsers give them ("Enter", "ArrowDown"), as Cypress types them. */
const KEYS: Record<string, string> = {
  enter: '{enter}',
  escape: '{esc}',
  esc: '{esc}',
  backspace: '{backspace}',
  delete: '{del}',
  space: ' ',
  arrowdown: '{downArrow}',
  arrowup: '{upArrow}',
  arrowleft: '{leftArrow}',
  arrowright: '{rightArrow}',
  home: '{home}',
  end: '{end}',
  pageup: '{pageUp}',
  pagedown: '{pageDown}',
};
