// Generated by Suite Builder from a crawl of the site. ReadActions for StatusCodesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { UserActions } from '../../../core/UserActions';
import { StatusCodesElements } from '../StatusCodesElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Values to read off StatusCodesPage. Each is a Cypress chain: .then((value) => ...) to use it.
 * The crawl does not know these: add elements to StatusCodesElements, then methods here.
 */
export class StatusCodesReadActions {
  /** The page's title. */
  title(): Cypress.Chainable<string> {
    return cy.title();
  }

  /** The page's address. */
  url(): Cypress.Chainable<string> {
    return cy.url();
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per value, e.g.:
  // orderNumber(): Cypress.Chainable<string> {
  //   return UserActions.readText(StatusCodesElements.ORDER_NUMBER_TEXT);
  // }
  // ==== END YOURS (actions) ====
}
