// Generated by Suite Builder from a crawl of the site. Locators for ChallengingDomPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.challengingdom;

import com.herokuapp.theinternet.tests.core.Headings;
import com.herokuapp.theinternet.tests.core.PageElement;
import org.openqa.selenium.By;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /challenging_dom.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ChallengingDomElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Challenging DOM": every crawled page of this type showed it. */
    CHALLENGING_DOM_HEADING(Headings.named("Challenging DOM")),
    /** Heading "Lorem": every crawled page of this type showed it. */
    LOREM_HEADING(Headings.named("Lorem")),
    /** Heading "Ipsum": every crawled page of this type showed it. */
    IPSUM_HEADING(Headings.named("Ipsum")),
    /** Heading "Dolor": every crawled page of this type showed it. */
    DOLOR_HEADING(Headings.named("Dolor")),
    /** Heading "Sit": every crawled page of this type showed it. */
    SIT_HEADING(Headings.named("Sit")),
    /** Heading "Amet": every crawled page of this type showed it. */
    AMET_HEADING(Headings.named("Amet")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(By.xpath("//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final By by;
    private final String label;

    ChallengingDomElements(By by) {
        this(by, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ChallengingDomElements(By by, String label) {
        this.by = by;
        this.label = label;
    }

    @Override
    public By by() {
        return by;
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(driver, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     return PageElement.of("RESULT_LINK", "the result " + name, By.xpath("//a[normalize-space()=" + Headings.literal(name) + "]"));
    // }
    // ==== END YOURS (extras) ====
}
