// Generated by Suite Builder from a crawl of the site. Locators for IframePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.iframe;

import com.herokuapp.theinternet.tests.core.Headings;
import com.herokuapp.theinternet.tests.core.PageElement;
import org.openqa.selenium.By;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /iframe.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum IframeElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "An iFrame containing the TinyMCE WYSIWYG Editor": every crawled page of this type showed it. */
    AN_I_FRAME_CONTAINING_THE_TINY_MCE_WYSIWYG_EDITOR_HEADING(Headings.named("An iFrame containing the TinyMCE WYSIWYG Editor")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** menuitem "File": seen by the crawl on /iframe. */
    FILE_BUTTON(By.xpath("//button[normalize-space()='File']")),
    /** menuitem "Edit": seen by the crawl on /iframe. */
    EDIT_BUTTON(By.xpath("//button[normalize-space()='Edit']")),
    /** menuitem "View": seen by the crawl on /iframe. */
    VIEW_BUTTON(By.xpath("//button[normalize-space()='View']")),
    /** menuitem "Format": seen by the crawl on /iframe. */
    FORMAT_BUTTON(By.xpath("//button[normalize-space()='Format']")),
    /** button "Undo": seen by the crawl on /iframe. */
    UNDO_BUTTON(By.xpath("//button[@aria-label='Undo']")),
    /** button "Redo": seen by the crawl on /iframe. */
    REDO_BUTTON(By.xpath("//button[@aria-label='Redo']")),
    /** button "Formats": seen by the crawl on /iframe. */
    FORMATS_BUTTON(By.xpath("//button[@aria-label='Formats']")),
    /** button "Bold": seen by the crawl on /iframe. */
    BOLD_BUTTON(By.xpath("//button[@aria-label='Bold']")),
    /** button "Italic": seen by the crawl on /iframe. */
    ITALIC_BUTTON(By.xpath("//button[@aria-label='Italic']")),
    /** button "Align left": seen by the crawl on /iframe. */
    ALIGN_LEFT_BUTTON(By.xpath("//button[@aria-label='Align left']")),
    /** button "Align center": seen by the crawl on /iframe. */
    ALIGN_CENTER_BUTTON(By.xpath("//button[@aria-label='Align center']")),
    /** button "Align right": seen by the crawl on /iframe. */
    ALIGN_RIGHT_BUTTON(By.xpath("//button[@aria-label='Align right']")),
    /** button "Justify": seen by the crawl on /iframe. */
    JUSTIFY_BUTTON(By.xpath("//button[@aria-label='Justify']")),
    /** button "Decrease indent": seen by the crawl on /iframe. */
    DECREASE_INDENT_BUTTON(By.xpath("//button[@aria-label='Decrease indent']")),
    /** button "Increase indent": seen by the crawl on /iframe. */
    INCREASE_INDENT_BUTTON(By.xpath("//button[@aria-label='Increase indent']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(By.xpath("//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final By by;
    private final String label;

    IframeElements(By by) {
        this(by, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    IframeElements(By by, String label) {
        this.by = by;
        this.label = label;
    }

    @Override
    public By by() {
        return by;
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(driver, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     return PageElement.of("RESULT_LINK", "the result " + name, By.xpath("//a[normalize-space()=" + Headings.literal(name) + "]"));
    // }
    // ==== END YOURS (extras) ====
}
