// Generated by Suite Builder from a crawl of the site. The "Key Presses" form on KeyPressesPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what KeyPressesTasks.fillKeyPressesForm takes.
import { SiteConfig } from '../../core/SiteConfig';

/**
 * The "Key Presses" form on KeyPressesPage, as one value: its fields in page order, what
 * KeyPressesTasks.fillKeyPressesForm types and chooses. Change one field with a spread:
 * `{ ...KeyPresses.sample(), textField: '...' }`.
 */
export interface KeyPresses {
  textField: string;
}

export const KeyPresses = {
  /** Values any copy of the site takes, each plausible for its field; one can be set for a run: npx cypress run --expose textField=... */
  sample(): KeyPresses {
    return {
      textField: SiteConfig.value('textField', 'Test textField'),
    };
  },
};
