// Generated by Suite Builder from a crawl of the site. Links land on the pages they promise.
// EDIT RULES: do not edit this file; regenerating replaces all of it. It is rebuilt from the crawl. Stories go next to it, in this folder (ai/AI-README.md).
package com.herokuapp.theinternet.tests.cases;

import com.herokuapp.theinternet.tests.BaseTest;

import com.herokuapp.theinternet.tests.pages.disappearingelements.DisappearingElementsPage;
import com.herokuapp.theinternet.tests.pages.dynamicloading.DynamicLoadingPage;
import com.herokuapp.theinternet.tests.pages.frames.FramesPage;
import com.herokuapp.theinternet.tests.pages.home.HomePage;
import com.herokuapp.theinternet.tests.pages.infinitescrolldetail.InfiniteScrollDetailPage;
import com.herokuapp.theinternet.tests.pages.jqueryui.JqueryuiPage;
import com.herokuapp.theinternet.tests.pages.shiftingcontent.ShiftingContentPage;
import com.herokuapp.theinternet.tests.pages.shiftingcontentmenu.ShiftingContentMenuPage;
import com.herokuapp.theinternet.tests.pages.statuscodes.StatusCodesPage;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.StatusCodesDetailPage;
import com.herokuapp.theinternet.tests.pages.windows.WindowsPage;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/** The header and footer links, and links between page types found by the crawl, land where they should. */
@Tag("navigation")
class NavigationTest extends BaseTest {

    @Test
    @DisplayName("/ -> /tinymce lands on TinymcePage")
    void homeLinksToTinymce() {
        new HomePage(driver).open().click().goToTinymce().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /frames lands on FramesPage")
    void homeLinksToFrames() {
        new HomePage(driver).open().click().goToFrames().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /dropdown lands on DropdownPage")
    void homeLinksToDropdown() {
        new HomePage(driver).open().click().goToDropdown().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /notification_message lands on NotificationMessageRenderedPage")
    void homeLinksToNotificationMessageRendered() {
        new HomePage(driver).open().click().goToNotificationMessageRendered().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /challenging_dom lands on ChallengingDomPage")
    void homeLinksToChallengingDom() {
        new HomePage(driver).open().click().goToChallengingDom().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /javascript_alerts lands on JavascriptAlertsPage")
    void homeLinksToJavascriptAlerts() {
        new HomePage(driver).open().click().goToJavascriptAlerts().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /exit_intent lands on ExitIntentPage")
    void homeLinksToExitIntent() {
        new HomePage(driver).open().click().goToExitIntent().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /jqueryui/menu lands on JqueryuiMenuPage")
    void homeLinksToJqueryuiMenu() {
        new HomePage(driver).open().click().goToJqueryuiMenu().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /tables lands on TablesPage")
    void homeLinksToTables() {
        new HomePage(driver).open().click().goToTables().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /infinite_scroll lands on InfiniteScrollPage")
    void homeLinksToInfiniteScroll() {
        new HomePage(driver).open().click().goToInfiniteScroll().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /dynamic_loading lands on DynamicLoadingPage")
    void homeLinksToDynamicLoading() {
        new HomePage(driver).open().click().goToDynamicLoading().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /shadowdom lands on ShadowdomPage")
    void homeLinksToShadowdom() {
        new HomePage(driver).open().click().goToShadowdom().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /disappearing_elements lands on DisappearingElementsPage")
    void homeLinksToDisappearingElements() {
        new HomePage(driver).open().click().goToDisappearingElements().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /redirector lands on RedirectorPage")
    void homeLinksToRedirector() {
        new HomePage(driver).open().click().goToRedirector().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /geolocation lands on GeolocationPage")
    void homeLinksToGeolocation() {
        new HomePage(driver).open().click().goToGeolocation().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /add_remove_elements/ lands on AddRemoveElementsPage")
    void homeLinksToAddRemoveElements() {
        new HomePage(driver).open().click().goToAddRemoveElements().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /javascript_error lands on JavascriptErrorPage")
    void homeLinksToJavascriptError() {
        new HomePage(driver).open().click().goToJavascriptError().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /entry_ad lands on EntryAdPage")
    void homeLinksToEntryAd() {
        new HomePage(driver).open().click().goToEntryAd().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /status_codes lands on StatusCodesPage")
    void homeLinksToStatusCodes() {
        new HomePage(driver).open().click().goToStatusCodes().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /nested_frames lands on NestedFramesPage")
    void homeLinksToNestedFrames() {
        new HomePage(driver).open().click().goToNestedFrames().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /forgot_password lands on ForgotPasswordPage")
    void homeLinksToForgotPassword() {
        new HomePage(driver).open().click().goToForgotPassword().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /checkboxes lands on CheckboxesPage")
    void homeLinksToCheckboxes() {
        new HomePage(driver).open().click().goToCheckboxes().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /large lands on LargePage")
    void homeLinksToLarge() {
        new HomePage(driver).open().click().goToLarge().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /upload lands on UploadPage")
    void homeLinksToUpload() {
        new HomePage(driver).open().click().goToUpload().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /dynamic_content lands on DynamicContentPage")
    void homeLinksToDynamicContent() {
        new HomePage(driver).open().click().goToDynamicContent().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /shifting_content lands on ShiftingContentPage")
    void homeLinksToShiftingContent() {
        new HomePage(driver).open().click().goToShiftingContent().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /hovers lands on HoversPage")
    void homeLinksToHovers() {
        new HomePage(driver).open().click().goToHovers().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /abtest lands on AbtestPage")
    void homeLinksToAbtest() {
        new HomePage(driver).open().click().goToAbtest().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /key_presses lands on KeyPressesPage")
    void homeLinksToKeyPresses() {
        new HomePage(driver).open().click().goToKeyPresses().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /dynamic_controls lands on DynamicControlsPage")
    void homeLinksToDynamicControls() {
        new HomePage(driver).open().click().goToDynamicControls().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /typos lands on TyposPage")
    void homeLinksToTypos() {
        new HomePage(driver).open().click().goToTypos().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /context_menu lands on ContextMenuPage")
    void homeLinksToContextMenu() {
        new HomePage(driver).open().click().goToContextMenu().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /horizontal_slider lands on HorizontalSliderPage")
    void homeLinksToHorizontalSlider() {
        new HomePage(driver).open().click().goToHorizontalSlider().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /broken_images lands on BrokenImagesPage")
    void homeLinksToBrokenImages() {
        new HomePage(driver).open().click().goToBrokenImages().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /windows lands on WindowsPage")
    void homeLinksToWindows() {
        new HomePage(driver).open().click().goToWindows().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /floating_menu lands on FloatingMenuPage")
    void homeLinksToFloatingMenu() {
        new HomePage(driver).open().click().goToFloatingMenu().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /download lands on DownloadPage")
    void homeLinksToDownload() {
        new HomePage(driver).open().click().goToDownload().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /slow lands on SlowPage")
    void homeLinksToSlow() {
        new HomePage(driver).open().click().goToSlow().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /inputs lands on InputsPage")
    void homeLinksToInputs() {
        new HomePage(driver).open().click().goToInputs().verify().isLoaded();
    }

    @Test
    @DisplayName("/ -> /drag_and_drop lands on DragAndDropPage")
    void homeLinksToDragAndDrop() {
        new HomePage(driver).open().click().goToDragAndDrop().verify().isLoaded();
    }

    @Test
    @DisplayName("/frames -> /nested_frames lands on NestedFramesPage")
    void framesLinksToNestedFrames() {
        new FramesPage(driver).open().click().goToNestedFrames().verify().isLoaded();
    }

    @Test
    @DisplayName("/frames -> /iframe lands on IframePage")
    void framesLinksToIframe() {
        new FramesPage(driver).open().click().goToIframe().verify().isLoaded();
    }

    @Test
    @DisplayName("/infinite_scroll/18 -> /infinite_scroll/19 lands on InfiniteScrollDetailPage")
    void infiniteScrollDetailLinksToInfiniteScrollDetail() {
        new InfiniteScrollDetailPage(driver).open("18").click().goToInfiniteScrollDetail("19").verify().isLoaded();
    }

    @Test
    @DisplayName("/dynamic_loading -> /dynamic_loading/1 lands on DynamicLoadingDetailPage")
    void dynamicLoadingLinksToDynamicLoadingDetail() {
        new DynamicLoadingPage(driver).open().click().goToDynamicLoadingDetail("1").verify().isLoaded();
    }

    @Test
    @DisplayName("/disappearing_elements -> / lands on HomePage")
    void disappearingElementsLinksToHome() {
        new DisappearingElementsPage(driver).open().click().goToHome().verify().isLoaded();
    }

    @Test
    @DisplayName("/status_codes -> /status_codes/200 lands on StatusCodesDetailPage")
    void statusCodesLinksToStatusCodesDetail() {
        new StatusCodesPage(driver).open().click().goToStatusCodesDetail("200").verify().isLoaded();
    }

    @Test
    @DisplayName("/status_codes/301 -> /status_codes lands on StatusCodesPage")
    void statusCodesDetailLinksToStatusCodes() {
        new StatusCodesDetailPage(driver).open("301").click().goToStatusCodes().verify().isLoaded();
    }

    @Test
    @DisplayName("/shifting_content -> /shifting_content/image lands on ShiftingContentDetailPage")
    void shiftingContentLinksToShiftingContentDetail() {
        new ShiftingContentPage(driver).open().click().goToShiftingContentDetail("image").verify().isLoaded();
    }

    @Test
    @DisplayName("/shifting_content -> /shifting_content/menu lands on ShiftingContentMenuPage")
    void shiftingContentLinksToShiftingContentMenu() {
        new ShiftingContentPage(driver).open().click().goToShiftingContentMenu().verify().isLoaded();
    }

    @Test
    @DisplayName("/shifting_content/menu -> / lands on HomePage")
    void shiftingContentMenuLinksToHome() {
        new ShiftingContentMenuPage(driver).open().click().goToHome().verify().isLoaded();
    }

    @Test
    @DisplayName("/windows -> /windows/new lands on WindowsNewPage")
    void windowsLinksToWindowsNew() {
        new WindowsPage(driver).open().click().goToWindowsNew().verify().isLoaded();
    }

    @Test
    @DisplayName("/jqueryui -> /jqueryui/menu lands on JqueryuiMenuPage")
    void jqueryuiLinksToJqueryuiMenu() {
        new JqueryuiPage(driver).open().click().goToJqueryuiMenu().verify().isLoaded();
    }
}
