// Generated by Suite Builder from a crawl of the site. Checks for ChallengingDomPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.challengingdom.actions;

import com.herokuapp.theinternet.tests.pages.challengingdom.ChallengingDomPage;
import com.herokuapp.theinternet.tests.pages.challengingdom.ChallengingDomElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on ChallengingDomPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class ChallengingDomVerifyActions {
    private final Page page;

    public ChallengingDomVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public ChallengingDomVerifyActions isLoaded() {
        ChallengingDomPage here = new ChallengingDomPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public ChallengingDomVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Challenging DOM\", \"Lorem\", \"Ipsum\", \"Dolor\", \"Sit\", \"Amet\")",
                ChallengingDomElements.CHALLENGING_DOM_HEADING, ChallengingDomElements.LOREM_HEADING, ChallengingDomElements.IPSUM_HEADING, ChallengingDomElements.DOLOR_HEADING, ChallengingDomElements.SIT_HEADING, ChallengingDomElements.AMET_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(ChallengingDomElements.SOME_HEADING)}. */
    public ChallengingDomVerifyActions shows(ChallengingDomElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public ChallengingDomVerifyActions doesNotShow(ChallengingDomElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public ChallengingDomVerifyActions says(ChallengingDomElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public ChallengingDomVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public ChallengingDomVerifyActions holds(ChallengingDomElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public ChallengingDomVerifyActions isEmpty(ChallengingDomElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public ChallengingDomVerifyActions refusesEmpty(ChallengingDomElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public ChallengingDomVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, ChallengingDomElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
