// Generated by Suite Builder from a crawl of the site. Locators for DisappearingElementsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings } from '../../core/Headings';
import { byXPath, elements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /disappearing_elements.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const DisappearingElementsElements = elements({
  // Section headings the crawled pages of this type share. One a test does not use is harmless.
  /** Heading "Disappearing Elements": every crawled page of this type showed it. */
  DISAPPEARING_ELEMENTS_HEADING: Headings.named('Disappearing Elements'),

  // Links to other pages (from the crawl).
  /** Link "Home" (href /) to HomePage, seen by the crawl on /disappearing_elements. */
  HOME_LINK: byXPath('//a[@href=\'/\']'),

  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
