// Generated by Suite Builder from a crawl of the site. EnterActions for HorizontalSliderPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { SiteConfig } from '../../../core/SiteConfig';
import { UserActions } from '../../../core/UserActions';
import { HorizontalSliderElements } from '../HorizontalSliderElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on HorizontalSliderPage.
 * The crawl's own are below; add more (elements to HorizontalSliderElements, then methods here) in the YOURS block.
 */
export class HorizontalSliderEnterActions {
  /** Types into the range field "RANGE_FIELD_INPUT". */
  rangeField(text: string): HorizontalSliderEnterActions {
    UserActions.type(HorizontalSliderElements.RANGE_FIELD_INPUT, text);
    return this;
  }

  /** Empties the range field "RANGE_FIELD_INPUT". */
  clearRangeField(): HorizontalSliderEnterActions {
    UserActions.clear(HorizontalSliderElements.RANGE_FIELD_INPUT);
    return this;
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per field, e.g.:
  // email(text: string): HorizontalSliderEnterActions {
  //   UserActions.type(HorizontalSliderElements.EMAIL_INPUT, text);
  //   return this;
  // }
  // A password or other secret: SiteConfig.secret('password').then((p) => UserActions.typeSecret(HorizontalSliderElements.PASSWORD_INPUT, p));
  // A dropdown: UserActions.choose(HorizontalSliderElements.COUNTRY_SELECT, country);
  // ==== END YOURS (actions) ====
}
