// Generated by Suite Builder from a crawl of the site. Page object for TablesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { TablesElements } from './TablesElements';
import { TablesReadActions } from './actions/TablesReadActions';
import { TablesVerifyActions } from './actions/TablesVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /tables.
 * Stories call it:  "Sortable Data Tables" (the links that lead here).
 * Get here:         new TablesPage().open()
 *                   from HomePage: click().goToTables()
 * The crawl saw:    1 page of this type (/tables); it showed "Data Tables", "Example 1", "Last Name", "First Name", "Email", "Due".
 * Proven loaded by: the heading "Data Tables" and the heading "Example 1" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/tables.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/TablesPage/ and add what it shows to TablesElements.
 */
export class TablesPage extends LoadablePage<TablesPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 9a42ea1f
  static readonly PROVES_LOADED: readonly PageElement[] = [
    TablesElements.DATA_TABLES_HEADING,
    TablesElements.EXAMPLE_1_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('TablesPage');
  }

  /** Goes to /tables and waits until it has fully loaded. */
  open(): TablesPage {
    this.navigate(UrlPaths.TABLES);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.TABLES, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.TABLES}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(TablesPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${TablesPage.TITLE}"`);
    for (const element of TablesPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(TablesElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): TablesReadActions {
    return new TablesReadActions();
  }

  verify(): TablesVerifyActions {
    return new TablesVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
