// Generated by Suite Builder from a crawl of the site. Locators for TablesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings } from '../../core/Headings';
import { byXPath, elements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /tables.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const TablesElements = elements({
  // Section headings the crawled pages of this type share. One a test does not use is harmless.
  /** Heading "Data Tables": every crawled page of this type showed it. */
  DATA_TABLES_HEADING: Headings.named('Data Tables'),
  /** Heading "Example 1": every crawled page of this type showed it. */
  EXAMPLE_1_HEADING: Headings.named('Example 1'),
  /** Heading "Last Name": every crawled page of this type showed it. */
  LAST_NAME_HEADING: Headings.named('Last Name'),
  /** Heading "First Name": every crawled page of this type showed it. */
  FIRST_NAME_HEADING: Headings.named('First Name'),
  /** Heading "Email": every crawled page of this type showed it. */
  EMAIL_HEADING: Headings.named('Email'),
  /** Heading "Due": every crawled page of this type showed it. */
  DUE_HEADING: Headings.named('Due'),

  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
