// Generated by Suite Builder from a crawl of the site. Locators for ContextMenuPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.contextmenu;

import com.herokuapp.theinternet.tests.core.Headings;
import com.herokuapp.theinternet.tests.core.LocatorProvider;
import com.herokuapp.theinternet.tests.core.PageElement;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /context_menu.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ContextMenuElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Context Menu": every crawled page of this type showed it. */
    CONTEXT_MENU_HEADING(page -> Headings.named(page, "Context Menu")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    ContextMenuElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ContextMenuElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
