// Generated by Suite Builder from a crawl of the site. Page object for DragAndDropPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { DragAndDropElements } from './DragAndDropElements';
import { DragAndDropReadActions } from './actions/DragAndDropReadActions';
import { DragAndDropVerifyActions } from './actions/DragAndDropVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /drag_and_drop.
 * Stories call it:  "Drag and Drop" (the links that lead here).
 * Get here:         new DragAndDropPage().open()
 *                   from HomePage: click().goToDragAndDrop()
 * The crawl saw:    1 page of this type (/drag_and_drop); it showed "Drag and Drop".
 * Proven loaded by: the heading "Drag and Drop" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/drag_and_drop.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/DragAndDropPage/ and add what it shows to DragAndDropElements.
 */
export class DragAndDropPage extends LoadablePage<DragAndDropPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default cb527019
  static readonly PROVES_LOADED: readonly PageElement[] = [
    DragAndDropElements.DRAG_AND_DROP_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('DragAndDropPage');
  }

  /** Goes to /drag_and_drop and waits until it has fully loaded. */
  open(): DragAndDropPage {
    this.navigate(UrlPaths.DRAG_AND_DROP);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.DRAG_AND_DROP, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.DRAG_AND_DROP}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(DragAndDropPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${DragAndDropPage.TITLE}"`);
    for (const element of DragAndDropPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(DragAndDropElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): DragAndDropReadActions {
    return new DragAndDropReadActions();
  }

  verify(): DragAndDropVerifyActions {
    return new DragAndDropVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
