// Generated by Suite Builder from a crawl of the site. Page object for InfiniteScrollPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.infinitescroll;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.ClickableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.infinitescroll.actions.InfiniteScrollClickActions;
import com.herokuapp.theinternet.tests.pages.infinitescroll.actions.InfiniteScrollReadActions;
import com.herokuapp.theinternet.tests.pages.infinitescroll.actions.InfiniteScrollVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /infinite_scroll.
 * Stories call it:  "Infinite Scroll" (the links that lead here).
 * Get here:         new InfiniteScrollPage(driver).open()
 *                   from HomePage: click().goToInfiniteScroll()
 * The crawl saw:    1 page of this type (/infinite_scroll); it showed "Infinite Scroll".
 * Proven loaded by: the heading "Infinite Scroll" (isLoaded(), PROVES_LOADED: what a copy edit
 *                   leaves alone first).
 * As crawled:       crawl/pages/infinite_scroll.html (the page's HTML when crawled: check a locator
 *                   there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/InfiniteScrollPage/
 *                   (saved-pages/README.md) and add what it shows to InfiniteScrollElements.
 * </pre>
 */
public class InfiniteScrollPage extends LoadablePage<InfiniteScrollPage> implements
        ClickableAction<InfiniteScrollClickActions>,
        ReadableAction<InfiniteScrollReadActions>,
        VerifiableAction<InfiniteScrollVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "The Internet";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default c12321d3
    static final List<InfiniteScrollElements> PROVES_LOADED = List.of(
            InfiniteScrollElements.INFINITE_SCROLL_HEADING);
    // ==== END YOURS (load-proof) ====

    public InfiniteScrollPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to /infinite_scroll and waits until it has fully loaded. */
    public InfiniteScrollPage open() {
        navigate(UrlPaths.INFINITE_SCROLL);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(driver, UrlPaths.INFINITE_SCROLL);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + UrlPaths.INFINITE_SCROLL);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);

        if (!WaitActions.waitForTitle(driver, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + driver.getTitle() + "\", expected \"" + TITLE + "\"");
        }

        for (InfiniteScrollElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, InfiniteScrollElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public InfiniteScrollClickActions click() {
        return new InfiniteScrollClickActions(driver);
    }

    @Override
    public InfiniteScrollReadActions read() {
        return new InfiniteScrollReadActions(driver);
    }

    @Override
    public InfiniteScrollVerifyActions verify() {
        return new InfiniteScrollVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
