// Generated by Suite Builder from a crawl of the site. Which requests are ads, and refusing them in Chrome and Edge.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.core;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chromium.ChromiumDriver;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Ad networks, refused in every test (BaseTest) unless {@code -DblockAds=false}. Their full-page ads
 * take over the click a test makes (letcode.in: links landed on /forms#google_vignette, a Google ad
 * over the page), and they keep pages loading. They are not the site under test, and the crawl the
 * suite was built from never saw them (it refuses them too).
 *
 * <p>Chrome and Edge refuse them through their DevTools ({@code Network.setBlockedURLs}). Selenium
 * cannot refuse a request in Firefox or Safari: there the ads come through, and the run says so once.
 */
public final class Ads {
    /** Hosts of ad networks; their subdomains count too. */
    public static final List<String> HOSTS = List.of(
            "doubleclick.net", "googlesyndication.com", "googleadservices.com", "adservice.google.com",
            "googletagservices.com", "amazon-adsystem.com", "adnxs.com", "taboola.com",
            "outbrain.com", "criteo.com", "pubmatic.com", "rubiconproject.com",
            "moatads.com", "casalemedia.com", "smartadserver.com", "yieldmo.com",
            "sharethrough.com");

    private static boolean saidOnce;
    /** What block() did for this test's browser, for its evidence (run.txt). */
    private static final ThreadLocal<String> STATE = ThreadLocal.withInitial(() -> "not started");

    private Ads() {
    }

    /** Every host's address patterns, as the browser takes them: the host itself, and any subdomain. */
    public static List<String> patterns() {
        List<String> out = new ArrayList<>();
        for (List<String> hosts : List.of(HOSTS, MORE_HOSTS)) {
            for (String host : hosts) {
                out.add("*://" + host + "/*");
                out.add("*://*." + host + "/*");
            }
        }
        return out;
    }

    /** Whether this run refuses ads: -DblockAds, true unless set to false. */
    public static boolean wanted() {
        return Boolean.parseBoolean(System.getProperty("blockAds", "true"));
    }

    /**
     * Refuses every request to an ad network in this browser, when the run wants it and the browser
     * can (Chrome, Edge); {@link #state()} then says what was done.
     */
    public static void block(WebDriver driver) {
        if (!wanted()) {
            STATE.set("allowed (-DblockAds=false)");
        } else if (driver instanceof ChromiumDriver chromium) {
            chromium.executeCdpCommand("Network.enable", Map.of());
            chromium.executeCdpCommand("Network.setBlockedURLs", Map.of("urls", patterns()));
            STATE.set("blocked");
        } else {
            noteOnce();
            STATE.set("allowed (Selenium cannot refuse them in this browser)");
        }
    }

    /** What block() did for this test's browser: "blocked", or "allowed" and why. */
    public static String state() {
        return STATE.get();
    }

    private static synchronized void noteOnce() {
        if (saidOnce) return;
        saidOnce = true;
        System.out.println("Note: ads come through in this browser (Selenium refuses them only in Chrome and Edge); a test whose click an ad takes over fails for that.");
    }

    // ==== YOURS (more-hosts): safe to edit; regenerating keeps what is between these lines ====
    /** More hosts to block on this site (an ad or tracking network the list above lacks). */
    public static final List<String> MORE_HOSTS = List.of();
    // ==== END YOURS (more-hosts) ====
}
