// Generated by Suite Builder from a crawl of the site. Finds the element a visitor sees: the first visible match.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.core;

import org.openqa.selenium.By;
import org.openqa.selenium.ElementNotInteractableException;
import org.openqa.selenium.InvalidSelectorException;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.WebElement;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Finding elements the way a visitor sees them: the first visible match. Sites repeat links in hover
 * menus, mobile menus and hidden tabs, and a hidden copy found first can't be clicked. The browser's
 * implicit wait is off (BaseTest): these wait, for as long as {@link WaitActions#elementTimeout()},
 * and say what they waited for.
 */
public final class Find {
    private Find() {
    }

    /** The element, once it is visible; fails naming it after the wait. */
    public static WebElement visible(WebDriver driver, PageElement element) {
        return visible(driver, element.by(), element.label());
    }

    /**
     * The first visible match, once there is one; after the wait, fails naming it. An AssertionError, not
     * Selenium's NoSuchElementException: Selenium adds build, system and driver lines to its own
     * exceptions' messages, and this message is what the step log shows a person.
     */
    public static WebElement visible(WebDriver driver, By by, String label) {
        WebElement[] found = new WebElement[1];
        boolean shown = WaitActions.until(() -> (found[0] = visibleOrReveal(driver, by)) != null, WaitActions.elementTimeout());
        if (!shown) {
            throw new AssertionError(label + " was not shown within " + WaitActions.seconds(WaitActions.elementTimeout()) + " s: it is not on the page, or only where a visitor cannot see it (a closed menu, another slide, a layout for another screen size) (" + by + ")");
        }
        return found[0];
    }

    /** The first visible match now, or null. Never waits; throws only on a locator that is not valid. */
    public static WebElement visibleNow(WebDriver driver, By by) {
        try {
            // A lookup on the page comes out of a frame an earlier lookup went into (Frames).
            Frames.page(driver);
            List<WebElement> all = driver.findElements(by);
            for (WebElement e : all) {
                if (isShown(e)) return e;
            }
        } catch (InvalidSelectorException e) {
            throw invalid(by, e);
        } catch (WebDriverException e) {
            // a page in the middle of changing: nothing visible now
        }
        return null;
    }

    /**
     * The first visible match now; when there is none but a match is in the page, the first is
     * scrolled to the middle of the window, as a visitor scrolls to it, and null. A page that fades a
     * section in as it is scrolled to (opacity 0 until then, which Selenium counts as not displayed)
     * shows it by the next look (Site G, 2026-10-03: nine tests waited for headings below the fold).
     * For a wait that expects the element shown; one that expects it gone reads visibleNow.
     */
    public static WebElement visibleOrReveal(WebDriver driver, By by) {
        WebElement shown = visibleNow(driver, by);
        if (shown != null) return shown;
        try {
            List<WebElement> all = driver.findElements(by);
            if (!all.isEmpty()) toTheMiddle(driver, all.get(0));
        } catch (WebDriverException e) {
            // a page in the middle of changing: the next look tries again
        }
        return null;
    }

    /**
     * A locator that is not valid, said as one, not as "not shown" after a wait no wait can cure.
     * (Selenium takes the first match of a locator that matches several: that stays unseen here.)
     */
    public static AssertionError invalid(By by, InvalidSelectorException e) {
        String first = String.valueOf(e.getMessage()).lines().findFirst().orElse("");
        return new AssertionError("The locator " + by + " is not valid: " + first, e);
    }

    /** True when something it finds is visible now. */
    public static boolean anyVisible(WebDriver driver, By by) {
        return visibleNow(driver, by) != null;
    }

    /**
     * Clicks the first visible match: a generated link's click (the page's click actions log the
     * step). Brought to the middle of the window first, at once ({@link #toTheMiddle}). Tried again
     * while something covers it or the page redraws it, until the element timeout.
     */
    public static void click(WebDriver driver, By by, String label) {
        long end = System.currentTimeMillis() + WaitActions.elementTimeout();
        WebElement last = null;
        while (true) {
            try {
                last = visible(driver, by, label);
                toTheMiddle(driver, last);
                last.click();
                return;
            } catch (ElementNotInteractableException | StaleElementReferenceException notYet) {
                if (System.currentTimeMillis() >= end) throw notClickable(label, notYet, onTopOf(driver, last));
                WaitActions.until(() -> false, 100);
            }
        }
    }

    /**
     * Scrolls the element to the middle of the window, at once. Chrome's driver scrolls an element
     * into view and clicks straight away; on a page that scrolls smoothly (CSS scroll-behavior:
     * smooth) it clicks before the page has moved, below the window (letcode.in, 2026-10-02: "not
     * clickable at point (1121, 1657)" in a window 749 high). The middle also keeps it clear of a
     * fixed header or footer. Playwright and Cypress scroll this way themselves.
     */
    public static void toTheMiddle(WebDriver driver, WebElement element) {
        try {
            ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block: 'center', inline: 'center', behavior: 'instant'});", element);
        } catch (WebDriverException ignored) {
            // the click then scrolls as the driver does
        }
    }

    /** What is at the element's middle, when something other than it is: the cover, as its tag and class. Empty when nothing is. */
    public static String onTopOf(WebDriver driver, WebElement element) {
        if (element == null) return "";
        try {
            Object cover = ((JavascriptExecutor) driver).executeScript("const e = arguments[0], r = e.getBoundingClientRect();"
                    + " const top = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);"
                    + " if (!top || e === top || e.contains(top)) return '';"
                    + " return '<' + top.tagName.toLowerCase() + (top.id ? ' id=\"' + top.id + '\"' : '')"
                    + " + (typeof top.className === 'string' && top.className ? ' class=\"' + top.className.slice(0, 60) + '\"' : '') + '>';", element);
            return cover == null ? "" : cover.toString();
        } catch (WebDriverException gone) {
            return "";
        }
    }

    /** Shown, but it would not take the click (or the typing) in time: said in words, with Selenium's own first line. */
    public static AssertionError notClickable(String label, RuntimeException cause) {
        return notClickable(label, cause, "");
    }

    /** The same, naming what covers it when that is known ({@link #onTopOf}). */
    public static AssertionError notClickable(String label, RuntimeException cause, String cover) {
        String selenium = String.valueOf(cause.getMessage()).split("\n")[0];
        return new AssertionError(label + " was shown but could not be clicked within " + WaitActions.seconds(WaitActions.elementTimeout())
                + " s: something covers it (a banner, a sticky header, a pop-up), or it kept moving (Selenium saw: " + selenium + (cover.isEmpty() ? "" : "; on top of it: " + cover) + ")", cause);
    }

    /** True when the element is still in the page and displayed; false once it went away. */
    public static boolean isShown(WebElement e) {
        try {
            return e.isDisplayed();
        } catch (StaleElementReferenceException gone) {
            return false;
        }
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
