// Generated by Suite Builder from a crawl of the site. Finds elements inside frames, by the frame path the crawl recorded.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.core;

import org.openqa.selenium.By;
import org.openqa.selenium.SearchContext;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Elements inside frames (an iframe, a frameset): the frame path the crawl recorded, each frame
 * element's XPath in the document that holds it, outermost first.
 * {@code Frames.in(Headings.named("Card details"), "//iframe[@id='pay']")} finds the heading inside
 * that frame. Selenium searches only the frame it is in, so the context is made explicit here, by
 * construction: a lookup inside a frame goes to the page, then into each frame on its path; the next
 * lookup on the page itself comes back out first ({@link #page}). Code that switches frames on its
 * own (driver.switchTo().frame(...)) is left as it is.
 */
public final class Frames {
    /** Whether the last lookup went into a frame, and left the driver there. */
    private static final ThreadLocal<Boolean> INSIDE = ThreadLocal.withInitial(() -> false);

    private Frames() {
    }

    /** The element, found inside the frame at the end of the path. */
    public static By in(By element, String... path) {
        return new Inside(element, path);
    }

    /** Back on the page, when a lookup inside a frame left the driver in it. Every lookup calls this first. */
    public static void page(SearchContext context) {
        if (INSIDE.get() && context instanceof WebDriver driver) {
            driver.switchTo().defaultContent();
            INSIDE.set(false);
        }
    }

    private static final class Inside extends By {
        private final By element;
        private final String[] path;

        Inside(By element, String[] path) {
            this.element = element;
            this.path = path;
        }

        @Override
        public List<WebElement> findElements(SearchContext context) {
            WebDriver driver = (WebDriver) context;
            driver.switchTo().defaultContent();
            for (String frame : path) driver.switchTo().frame(driver.findElement(By.xpath(frame)));
            INSIDE.set(true);
            return driver.findElements(element);
        }

        @Override
        public String toString() {
            return element + " in frame " + String.join(" >> ", path);
        }
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
