// Generated by Suite Builder from a crawl of the site. Base class of every page class.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.core;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * A page that knows when it has loaded. {@link #get()} waits until it has, or throws an Error that
 * says what was not ready: the URL, the page load, the title, or the page's key elements.
 * Page objects are made fresh after each navigation: {@code new SomePage(driver).get()}.
 */
public abstract class LoadablePage<T extends LoadablePage<T>> {
    protected final WebDriver driver;

    protected LoadablePage(WebDriver driver) {
        this.driver = driver;
    }

    /** Brings the page up if needed. open() navigates, and clicks arrive here, so most pages need nothing. */
    protected abstract void load();

    /** Throws an Error, saying what, unless the page has fully loaded. */
    protected abstract void isLoaded() throws Error;

    /** Waits until this page has fully loaded; throws an Error saying what was not ready. */
    @SuppressWarnings("unchecked")
    public T get() {
        load();
        // Opened or clicked to, a page that answered an error fails as one, not as a page that looks wrong.
        try {
            isLoaded();
        } catch (Error notLoaded) {
            failOnErrorStatus(recordedStatus(), pathNow());
            throw notLoaded;
        }
        failOnErrorStatus(recordedStatus(), pathNow());
        Timings.record(name(), pathNow(), navigationTimes(), crawlSettledMs());
        StepLog.note("now on " + describe());
        return (T) this;
    }

    /**
     * Goes to a path of the site and gets the cookie banner out of the way; isLoaded() does the waiting.
     * The browser returns as soon as the page's HTML is read (BaseTest's page load strategy: eager),
     * so the banner is dealt with while images and scripts are still coming.
     */
    protected void navigate(String path) {
        StepLog.step("Open " + describe() + " (" + path + ")");
        driver.get(SiteConfig.url(path));
        CookieBanner.accept(driver);
    }

    /**
     * The page's HTTP status, as the browser recorded it (Navigation Timing); 0 where it records none
     * (Safari), or where the site's own script drew the page after a click (a single-page app): the record
     * is then the first page's. Selenium never sees the status; the browser does.
     */
    private int recordedStatus() {
        Object status = ((JavascriptExecutor) driver).executeScript("const n = performance.getEntriesByType('navigation')[0]; return n && n.responseStatus && new URL(n.name).pathname === location.pathname ? n.responseStatus : 0;");
        return status instanceof Number ? ((Number) status).intValue() : 0;
    }

    /** The path the browser is on now, for messages. */
    private String pathNow() {
        return java.net.URI.create(driver.getCurrentUrl()).getPath();
    }

    /**
     * Fails when the site answered an error (4xx or 5xx) for this page, in words: a server error at
     * the right address is not a page that loaded.
     */
    protected void failOnErrorStatus(int status, String path) {
        int known = knownStatus();
        if (known != 0 && status == known) {
            noteOnce("known " + status, describe() + " answered HTTP " + status + " at " + path + ", as in the crawl: a known defect (KNOWN-ISSUES.md, SITE-01)");
            return;
        }
        if (known != 0 && status > 0 && status < 400) {
            noteOnce("fixed " + status, describe() + " answers HTTP " + status + " now, not " + known + " as in the crawl: SITE-01 is fixed here."
                    + " Take it out of KNOWN-ISSUES.md; a rebuild from a new crawl drops the known status.");
            return;
        }
        if (status < 400) return;
        throw new AssertionError(describe() + " answered HTTP " + status + " at " + path + ": "
                + (status >= 500 ? "a server error on the site" : "the site did not serve the page") + ", not a page that loaded");
    }

    /** The status this page type is known to answer, a defect the crawl found (KNOWN-ISSUES.md, SITE-01); 0 for none. Page classes say theirs. */
    protected int knownStatus() {
        return 0;
    }

    private String said;

    /**
     * A note said once for this page object, however many times its status is checked, and at however
     * many addresses (one that redirects to add its trailing slash is checked at both).
     */
    private void noteOnce(String what, String note) {
        if (what.equals(said)) return;
        said = what;
        StepLog.note(note);
    }

    /** What the crawl timed of this page type's pages after their load event, in ms; -1 when it did not. Page classes say theirs. */
    protected long crawlSettledMs() {
        return -1;
    }

    /**
     * When the page was ready (now), its first byte, DOM loaded and load event, in ms from the start of
     * its navigation, as "ready,firstByte,domLoaded,load"; "" where the browser records none.
     */
    private String navigationTimes() {
        Object times = ((JavascriptExecutor) driver).executeScript("const n = performance.getEntriesByType('navigation')[0]; return n ? [performance.now(), n.responseStart, n.domContentLoadedEventEnd, n.loadEventEnd, performance.timeOrigin].map(Math.round).join(',') : '';");
        return times instanceof String ? (String) times : "";
    }

    /** The name of this page type, for error messages. */
    protected String name() {
        return getClass().getSimpleName();
    }

    /** This page type in plain English, for steps: ServicesDetailPage -> "the services detail page". */
    public String describe() {
        String n = getClass().getSimpleName();
        StringBuilder out = new StringBuilder("the ");
        for (int i = 0; i < n.length(); i++) {
            char c = n.charAt(i);
            if (i > 0 && Character.isUpperCase(c)) out.append(' ');
            out.append(Character.toLowerCase(c));
        }
        return out.toString();
    }

    public WebDriver driver() {
        return driver;
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // What every page of this site shares (a common dialog to close, say) goes here.
    // ==== END YOURS (extras) ====
}
