// Generated by Suite Builder from a crawl of the site. ReadActions for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.forgotpassword.actions;

import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.forgotpassword.ForgotPasswordElements;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Values to read off ForgotPasswordPage.
 * The crawl does not know these: add elements to ForgotPasswordElements, then methods here.
 */
public class ForgotPasswordReadActions {
    private final WebDriver driver;

    public ForgotPasswordReadActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page's title. */
    public String title() {
        return driver.getTitle();
    }

    /** The page's address. */
    public String url() {
        return driver.getCurrentUrl();
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per value, e.g.:
    // public String orderNumber() {
    //     return UserActions.readText(driver, ForgotPasswordElements.ORDER_NUMBER_TEXT);
    // }
    // ==== END YOURS (actions) ====
}
