// Generated by Suite Builder from a crawl of the site. ReadActions for EntryAdPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.entryad.actions;

import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.entryad.EntryAdElements;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Values to read off EntryAdPage.
 * The crawl does not know these: add elements to EntryAdElements, then methods here.
 */
public class EntryAdReadActions {
    private final Page page;

    public EntryAdReadActions(Page page) {
        this.page = page;
    }

    /** The page's title. */
    public String title() {
        return page.title();
    }

    /** The page's address. */
    public String url() {
        return page.url();
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per value, e.g.:
    // public String orderNumber() {
    //     return UserActions.readText(page, EntryAdElements.ORDER_NUMBER_TEXT);
    // }
    // ==== END YOURS (actions) ====
}
