// Generated by Suite Builder from a crawl of the site. Checks for EntryAdPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.entryad.actions;

import com.herokuapp.theinternet.tests.pages.entryad.EntryAdPage;
import com.herokuapp.theinternet.tests.pages.entryad.EntryAdElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on EntryAdPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class EntryAdVerifyActions {
    private final Page page;

    public EntryAdVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public EntryAdVerifyActions isLoaded() {
        EntryAdPage here = new EntryAdPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public EntryAdVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Entry Ad\", \"This is a modal window\")",
                EntryAdElements.ENTRY_AD_HEADING, EntryAdElements.THIS_IS_A_MODAL_WINDOW_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(EntryAdElements.SOME_HEADING)}. */
    public EntryAdVerifyActions shows(EntryAdElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public EntryAdVerifyActions doesNotShow(EntryAdElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public EntryAdVerifyActions says(EntryAdElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public EntryAdVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public EntryAdVerifyActions holds(EntryAdElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public EntryAdVerifyActions isEmpty(EntryAdElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public EntryAdVerifyActions refusesEmpty(EntryAdElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public EntryAdVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, EntryAdElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
