// Generated by Suite Builder from a crawl of the site. Click actions for DynamicControlsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Find } from '../../../core/Find';
import { StepLog } from '../../../core/StepLog';
import { UserActions } from '../../../core/UserActions';
import { DynamicControlsElements } from '../DynamicControlsElements';
import { DynamicControlsPage } from '../DynamicControlsPage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on DynamicControlsPage. Clicks that change page return the next page; others return this. */
export class DynamicControlsClickActions {
  /** Clicks the button "Remove". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
  remove(): DynamicControlsPage {
    UserActions.click(DynamicControlsElements.REMOVE_BUTTON);
    return new DynamicControlsPage();
  }

  /** Clicks the button "Enable". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
  enable(): DynamicControlsPage {
    UserActions.click(DynamicControlsElements.ENABLE_BUTTON);
    return new DynamicControlsPage();
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
  // acceptTerms(): DynamicControlsClickActions {
  //   UserActions.click(DynamicControlsElements.ACCEPT_BUTTON);
  //   return this;
  // }
  // ==== END YOURS (actions) ====
}
