// Generated by Suite Builder from a crawl of the site. Click actions for ShiftingContentPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.shiftingcontent.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.shiftingcontent.ShiftingContentElements;
import com.herokuapp.theinternet.tests.pages.shiftingcontentdetail.ShiftingContentDetailPage;
import com.herokuapp.theinternet.tests.pages.shiftingcontentmenu.ShiftingContentMenuPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on ShiftingContentPage. Clicks that change page return the next page; others return this. */
public class ShiftingContentClickActions {
    private final WebDriver driver;

    public ShiftingContentClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks a link to ShiftingContentDetailPage (e.g. Example 2: An image) and waits for it. */
    public ShiftingContentDetailPage goToShiftingContentDetail(String name) {
        UserActions.click(driver, ShiftingContentElements.getShiftingContentDetailLink(name));
        return new ShiftingContentDetailPage(driver).get();
    }

    /** Clicks the link to ShiftingContentMenuPage (Example 1: Menu Element) and waits for it. */
    public ShiftingContentMenuPage goToShiftingContentMenu() {
        UserActions.click(driver, ShiftingContentElements.SHIFTING_CONTENT_MENU_LINK);
        return new ShiftingContentMenuPage(driver).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public ShiftingContentVerifyActions verify() {
        return new ShiftingContentVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public ShiftingContentClickActions acceptTerms() {
    //     UserActions.click(driver, ShiftingContentElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
