// Generated by Suite Builder from a crawl of the site. Page object for HoversPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { HoversElements } from './HoversElements';
import { HoversReadActions } from './actions/HoversReadActions';
import { HoversVerifyActions } from './actions/HoversVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /hovers.
 * Stories call it:  "Hovers" (the links that lead here).
 * Get here:         new HoversPage().open()
 *                   from HomePage: click().goToHovers()
 * The crawl saw:    1 page of this type (/hovers); it showed "Hovers".
 * Proven loaded by: the heading "Hovers" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/hovers.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/HoversPage/ and add what it shows to HoversElements.
 */
export class HoversPage extends LoadablePage<HoversPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 518dc873
  static readonly PROVES_LOADED: readonly PageElement[] = [
    HoversElements.HOVERS_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('HoversPage');
  }

  /** Goes to /hovers and waits until it has fully loaded. */
  open(): HoversPage {
    this.navigate(UrlPaths.HOVERS);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.HOVERS, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.HOVERS}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(HoversPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${HoversPage.TITLE}"`);
    for (const element of HoversPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(HoversElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): HoversReadActions {
    return new HoversReadActions();
  }

  verify(): HoversVerifyActions {
    return new HoversVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
