// Generated by Suite Builder from a crawl of the site. Page object for InfiniteScrollDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.infinitescrolldetail;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.ClickableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.infinitescrolldetail.actions.InfiniteScrollDetailClickActions;
import com.herokuapp.theinternet.tests.pages.infinitescrolldetail.actions.InfiniteScrollDetailReadActions;
import com.herokuapp.theinternet.tests.pages.infinitescrolldetail.actions.InfiniteScrollDetailVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 34 pages, like /infinite_scroll/18,
 *                   /infinite_scroll/19, /infinite_scroll/20.
 * Get here:         new InfiniteScrollDetailPage(driver).open("18")
 *                   from InfiniteScrollPage: click().goToInfiniteScrollDetail("18")
 * The crawl saw:    33 pages of this type (/infinite_scroll/18, /infinite_scroll/19,
 *                   /infinite_scroll/20, ...).
 * Proven loaded by: its address and title only: add a key element to PROVES_LOADED.
 * As crawled:       crawl/pages/infinite_scroll/18.html, crawl/pages/infinite_scroll/19.html, ...
 *                   (the page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/InfiniteScrollDetailPage/
 *                   (saved-pages/README.md) and add what it shows to InfiniteScrollDetailElements.
 * </pre>
 */
public class InfiniteScrollDetailPage extends LoadablePage<InfiniteScrollDetailPage> implements
        ClickableAction<InfiniteScrollDetailClickActions>,
        ReadableAction<InfiniteScrollDetailReadActions>,
        VerifiableAction<InfiniteScrollDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/infinite_scroll/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 901d7d03
    public static final List<String> EXAMPLES = List.of(
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had no heading or structure in common, so add a key element here. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 73d8f417
    static final List<InfiniteScrollDetailElements> PROVES_LOADED = List.of();
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public InfiniteScrollDetailPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public InfiniteScrollDetailPage open(String name) {
        expectedPath = UrlPaths.infiniteScrollDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(driver, expectedPath)
                : WaitActions.waitForUrlShape(driver, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);


        for (InfiniteScrollDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, InfiniteScrollDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public InfiniteScrollDetailClickActions click() {
        return new InfiniteScrollDetailClickActions(driver);
    }

    @Override
    public InfiniteScrollDetailReadActions read() {
        return new InfiniteScrollDetailReadActions(driver);
    }

    @Override
    public InfiniteScrollDetailVerifyActions verify() {
        return new InfiniteScrollDetailVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
