// Generated by Suite Builder from a crawl of the site. Locators for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.forgotpassword;

import com.herokuapp.theinternet.tests.core.Headings;
import com.herokuapp.theinternet.tests.core.PageElement;
import org.openqa.selenium.By;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /forgot_password.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ForgotPasswordElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Forgot Password": every crawled page of this type showed it. */
    FORGOT_PASSWORD_HEADING(Headings.named("Forgot Password")),

    // "forgot_password" form (from the crawl: nothing was typed, clicked or sent).
    /** text field "E-mail": seen by the crawl on /forgot_password. */
    E_MAIL_INPUT(By.xpath("//input[@id='email']")),
    /** button "Retrieve password": seen by the crawl on /forgot_password. */
    RETRIEVE_PASSWORD_BUTTON(By.xpath("//button[@id='form_submit']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(By.xpath("//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final By by;
    private final String label;

    ForgotPasswordElements(By by) {
        this(by, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ForgotPasswordElements(By by, String label) {
        this.by = by;
        this.label = label;
    }

    @Override
    public By by() {
        return by;
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(driver, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     return PageElement.of("RESULT_LINK", "the result " + name, By.xpath("//a[normalize-space()=" + Headings.literal(name) + "]"));
    // }
    // ==== END YOURS (extras) ====
}
