// Generated by Suite Builder from a crawl of the site. Checks for RedirectorPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.redirector.actions;

import com.herokuapp.theinternet.tests.pages.redirector.RedirectorPage;
import com.herokuapp.theinternet.tests.pages.redirector.RedirectorElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on RedirectorPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class RedirectorVerifyActions {
    private final Page page;

    public RedirectorVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public RedirectorVerifyActions isLoaded() {
        RedirectorPage here = new RedirectorPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public RedirectorVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Redirection\")",
                RedirectorElements.REDIRECTION_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(RedirectorElements.SOME_HEADING)}. */
    public RedirectorVerifyActions shows(RedirectorElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public RedirectorVerifyActions doesNotShow(RedirectorElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public RedirectorVerifyActions says(RedirectorElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public RedirectorVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public RedirectorVerifyActions holds(RedirectorElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public RedirectorVerifyActions isEmpty(RedirectorElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public RedirectorVerifyActions refusesEmpty(RedirectorElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public RedirectorVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, RedirectorElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
