// Generated by Suite Builder from a crawl of the site. Click actions for UploadPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Find } from '../../../core/Find';
import { StepLog } from '../../../core/StepLog';
import { UserActions } from '../../../core/UserActions';
import { UploadElements } from '../UploadElements';
import { UploadPage } from '../UploadPage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on UploadPage. Clicks that change page return the next page; others return this. */
export class UploadClickActions {
  /** Clicks the button "Upload". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
  upload(): UploadPage {
    UserActions.click(UploadElements.UPLOAD_BUTTON);
    return new UploadPage();
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
  // acceptTerms(): UploadClickActions {
  //   UserActions.click(UploadElements.ACCEPT_BUTTON);
  //   return this;
  // }
  // ==== END YOURS (actions) ====
}
