// Generated by Suite Builder from a crawl of the site. Click actions for DisappearingElementsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.disappearingelements.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.disappearingelements.DisappearingElementsElements;
import com.herokuapp.theinternet.tests.pages.home.HomePage;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on DisappearingElementsPage. Clicks that change page return the next page; others return this. */
public class DisappearingElementsClickActions {
    private final Page page;

    public DisappearingElementsClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the link to HomePage (Home) and waits for it. */
    public HomePage goToHome() {
        UserActions.click(page, DisappearingElementsElements.HOME_LINK);
        return new HomePage(page).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public DisappearingElementsVerifyActions verify() {
        return new DisappearingElementsVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public DisappearingElementsClickActions acceptTerms() {
    //     UserActions.click(page, DisappearingElementsElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
