// Generated by Suite Builder from a crawl of the site. Page object for ShiftingContentDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.shiftingcontentdetail;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.shiftingcontentdetail.actions.ShiftingContentDetailReadActions;
import com.herokuapp.theinternet.tests.pages.shiftingcontentdetail.actions.ShiftingContentDetailVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 2 pages, like /shifting_content/list,
 *                   /shifting_content/image.
 * Get here:         new ShiftingContentDetailPage(driver).open("list")
 *                   from ShiftingContentPage: click().goToShiftingContentDetail("image")
 * The crawl saw:    2 pages of this type (/shifting_content/list, /shifting_content/image).
 * Proven loaded by: its address and title only: add a key element to PROVES_LOADED.
 * As crawled:       crawl/pages/shifting_content/list.html, crawl/pages/shifting_content/image.html
 *                   (the page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/ShiftingContentDetailPage/
 *                   (saved-pages/README.md) and add what it shows to ShiftingContentDetailElements.
 * </pre>
 */
public class ShiftingContentDetailPage extends LoadablePage<ShiftingContentDetailPage> implements
        ReadableAction<ShiftingContentDetailReadActions>,
        VerifiableAction<ShiftingContentDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/shifting_content/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 19ea2be9
    public static final List<String> EXAMPLES = List.of(
            "list",
            "image");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had no heading or structure in common, so add a key element here. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 412ffce9
    static final List<ShiftingContentDetailElements> PROVES_LOADED = List.of();
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public ShiftingContentDetailPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public ShiftingContentDetailPage open(String name) {
        expectedPath = UrlPaths.shiftingContentDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(driver, expectedPath)
                : WaitActions.waitForUrlShape(driver, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);


        for (ShiftingContentDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, ShiftingContentDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public ShiftingContentDetailReadActions read() {
        return new ShiftingContentDetailReadActions(driver);
    }

    @Override
    public ShiftingContentDetailVerifyActions verify() {
        return new ShiftingContentDetailVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
