// Generated by Suite Builder from a crawl of the site. Page object for DynamicLoadingDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamicloadingdetail;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.ClickableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.actions.DynamicLoadingDetailClickActions;
import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.actions.DynamicLoadingDetailReadActions;
import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.actions.DynamicLoadingDetailVerifyActions;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 2 pages, like /dynamic_loading/2,
 *                   /dynamic_loading/1.
 * Get here:         new DynamicLoadingDetailPage(page).open("2")
 *                   from DynamicLoadingPage: click().goToDynamicLoadingDetail("1")
 * The crawl saw:    2 pages of this type (/dynamic_loading/2, /dynamic_loading/1); every one showed
 *                   "Dynamically Loaded Page Elements".
 * Proven loaded by: the heading "Dynamically Loaded Page Elements" (isLoaded(), PROVES_LOADED: what
 *                   a copy edit leaves alone first).
 * As crawled:       crawl/pages/dynamic_loading/2.html, crawl/pages/dynamic_loading/1.html (the
 *                   page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/DynamicLoadingDetailPage/
 *                   (saved-pages/README.md) and add what it shows to DynamicLoadingDetailElements.
 * </pre>
 */
public class DynamicLoadingDetailPage extends LoadablePage<DynamicLoadingDetailPage> implements
        ClickableAction<DynamicLoadingDetailClickActions>,
        ReadableAction<DynamicLoadingDetailReadActions>,
        VerifiableAction<DynamicLoadingDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/dynamic_loading/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 24b6d611
    public static final List<String> EXAMPLES = List.of(
            "2",
            "1");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default e7878902
    static final List<DynamicLoadingDetailElements> PROVES_LOADED = List.of(
            DynamicLoadingDetailElements.DYNAMICALLY_LOADED_PAGE_ELEMENTS_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public DynamicLoadingDetailPage(Page page) {
        super(page);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public DynamicLoadingDetailPage open(String name) {
        expectedPath = UrlPaths.dynamicLoadingDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(page, expectedPath)
                : WaitActions.waitForUrlShape(page, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);


        for (DynamicLoadingDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, DynamicLoadingDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public DynamicLoadingDetailClickActions click() {
        return new DynamicLoadingDetailClickActions(page);
    }

    @Override
    public DynamicLoadingDetailReadActions read() {
        return new DynamicLoadingDetailReadActions(page);
    }

    @Override
    public DynamicLoadingDetailVerifyActions verify() {
        return new DynamicLoadingDetailVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
