// Generated by Suite Builder from a crawl of the site. Page object for SlowPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { SlowElements } from './SlowElements';
import { SlowReadActions } from './actions/SlowReadActions';
import { SlowVerifyActions } from './actions/SlowVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /slow.
 * Stories call it:  "Slow Resources" (the links that lead here).
 * Get here:         new SlowPage().open()
 *                   from HomePage: click().goToSlow()
 * The crawl saw:    1 page of this type (/slow); it showed "Slow Resources".
 * Proven loaded by: the heading "Slow Resources" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/slow.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/SlowPage/ and add what it shows to SlowElements.
 */
export class SlowPage extends LoadablePage<SlowPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 070cbe25
  static readonly PROVES_LOADED: readonly PageElement[] = [
    SlowElements.SLOW_RESOURCES_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('SlowPage');
  }

  /** Goes to /slow and waits until it has fully loaded. */
  open(): SlowPage {
    this.navigate(UrlPaths.SLOW);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.SLOW, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.SLOW}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(SlowPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${SlowPage.TITLE}"`);
    for (const element of SlowPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(SlowElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): SlowReadActions {
    return new SlowReadActions();
  }

  verify(): SlowVerifyActions {
    return new SlowVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
