// Generated by Suite Builder from a crawl of the site. CheckActions for CheckboxesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.checkboxes.actions;

import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.checkboxes.CheckboxesElements;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Checkboxes and radio buttons on CheckboxesPage: page.check() checks them, page.uncheck() unchecks them.
 * The crawl's own are below; add more (elements to CheckboxesElements, then methods here) in the YOURS block.
 */
public class CheckboxesCheckActions {
    private final Page page;
    private final boolean check;

    public CheckboxesCheckActions(Page page, boolean check) {
        this.page = page;
        this.check = check;
    }

    /** Ticks the checkbox "CHECKBOX" (page.check()), or unticks it (page.uncheck()). */
    public CheckboxesCheckActions checkbox() {
        UserActions.setTicked(page, CheckboxesElements.CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "CHECKBOX_2" (page.check()), or unticks it (page.uncheck()). */
    public CheckboxesCheckActions checkbox2() {
        UserActions.setTicked(page, CheckboxesElements.CHECKBOX_2, check);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public CheckboxesVerifyActions verify() {
        return new CheckboxesVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per checkbox or radio button, e.g.:
    // public CheckboxesCheckActions terms() {
    //     UserActions.setTicked(page, CheckboxesElements.TERMS_CHECKBOX, check);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
