// Generated by Suite Builder from a crawl of the site. EnterActions for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { SiteConfig } from '../../../core/SiteConfig';
import { UserActions } from '../../../core/UserActions';
import { ForgotPasswordElements } from '../ForgotPasswordElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on ForgotPasswordPage.
 * The crawl's own are below; add more (elements to ForgotPasswordElements, then methods here) in the YOURS block.
 */
export class ForgotPasswordEnterActions {
  /** Types into the text field "E-mail". */
  eMail(text: string): ForgotPasswordEnterActions {
    UserActions.type(ForgotPasswordElements.E_MAIL_INPUT, text);
    return this;
  }

  /** Empties the text field "E-mail". */
  clearEMail(): ForgotPasswordEnterActions {
    UserActions.clear(ForgotPasswordElements.E_MAIL_INPUT);
    return this;
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per field, e.g.:
  // email(text: string): ForgotPasswordEnterActions {
  //   UserActions.type(ForgotPasswordElements.EMAIL_INPUT, text);
  //   return this;
  // }
  // A password or other secret: SiteConfig.secret('password').then((p) => UserActions.typeSecret(ForgotPasswordElements.PASSWORD_INPUT, p));
  // A dropdown: UserActions.choose(ForgotPasswordElements.COUNTRY_SELECT, country);
  // ==== END YOURS (actions) ====
}
