// Generated by Suite Builder from a crawl of the site. What a failed test leaves behind, without being asked.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests;

import com.herokuapp.theinternet.tests.core.Ads;
import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.logging.LogEntry;
import org.openqa.selenium.logging.LogType;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What a failed test leaves behind, without any test asking (BaseTest wires it in), in
 * {@code target/failures/<TestClass>/<test>/}:
 * <pre>
 * screenshot.png   the browser window at the moment it failed
 * page.html        the DOM at that moment
 * console.txt      the page's console errors and warnings (Chrome and Edge report them; Firefox
 *                  and Safari don't, and it says so)
 * steps.txt        the steps in plain English, the failed one last, the error, the URL and title
 * run.txt          where and how it ran: site, browser, headless or not, time
 * </pre>
 * Saving never hides the failure: whatever cannot be saved is skipped. A passed test keeps nothing.
 * <p>
 * Each run starts clean: the run before moves to {@code target/failures-previous/} (so rerunning one
 * test does not lose the rest of a full run's evidence), and anything older is deleted.
 */
public final class Evidence {
    /** Where failed tests leave their evidence. */
    public static final Path FAILURES = Paths.get("target", "failures");
    /** The run before this one's failures: one run back, never more. */
    public static final Path PREVIOUS = Paths.get("target", "failures-previous");
    private static boolean cleared;

    private final WebDriver driver;
    private final String testClass;
    private final String testName;
    private final String displayName;
    /** "try-1" while it saves a retried test's first try (G-135): beside the second's, which keeps it. */
    private String tried = "";
    /** The page's scripts that did not load (ads aside), and why: a page that draws itself with one stays blank. */
    private final List<String> failedScripts = java.util.Collections.synchronizedList(new ArrayList<>());

    /** Starts watching a test. */
    Evidence(WebDriver driver, String testClass, String testName, String displayName) {
        this.driver = driver;
        this.testClass = testClass;
        this.testName = testName;
        this.displayName = displayName;
        startClean();
    }

    /** Saves what a failed test leaves behind, and returns the folder. */
    Path failed(Throwable cause, String browser) {
        Path dir = tried.isEmpty() ? FAILURES.resolve(testClass).resolve(testName) : FAILURES.resolve(testClass).resolve(testName).resolve(tried);
        try {
            clearKeeping(dir, FIRST_TRY);
            Files.createDirectories(dir);
        } catch (IOException e) {
            return dir;
        }
        // A page that stopped answering answers nothing more: a screenshot, its source and its console would
        // each wait out the timeout again, a minute and a half a failure (Ghost's Selenium run, 2026-10-04).
        if (String.valueOf(cause.getMessage()).contains("Timed out receiving message from renderer")) {
            String why = cause.getMessage();
            String firstLine = why.indexOf('\n') < 0 ? why : why.substring(0, why.indexOf('\n')).strip();
            attempt(() -> write(dir.resolve("page.html"), "<!-- The page stopped answering the browser (" + firstLine + "): no screenshot, source or console could be taken. -->\n"));
        } else {
            attempt(() -> Files.write(dir.resolve("screenshot.png"), ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
            attempt(() -> write(dir.resolve("page.html"), driver.getPageSource()));
            attempt(() -> write(dir.resolve("console.txt"), console()));
        }
        attempt(() -> write(dir.resolve("steps.txt"), steps(cause)));
        attempt(() -> write(dir.resolve("run.txt"), String.join("\n",
                "Test:     " + testClass + " / " + displayName,
                "Site:     " + SiteConfig.baseUrl(),
                "Browser:  " + browser
                        + (Boolean.parseBoolean(System.getProperty("headed", "false")) ? ", headed" : ", headless"),
                "Ads:      " + Ads.state(),
                "When:     " + Instant.now(),
                "Java:     " + System.getProperty("java.version") + " on " + System.getProperty("os.name"),
                "Suite:    see crawl/manifest.json for the Suite Builder version and crawl it came from",
                "")));
        return dir;
    }

    /** The console's errors and warnings, where the browser reports them. */
    private String console() {
        List<String> lines = new ArrayList<>();
        try {
            for (LogEntry entry : driver.manage().logs().get(LogType.BROWSER)) {
                String level = entry.getLevel().getName();
                if (level.equals("SEVERE") || level.equals("WARNING")) lines.add(level.toLowerCase() + ": " + entry.getMessage());
                noteFailedScript(entry.getMessage());
            }
        } catch (RuntimeException e) {
            return "This browser does not report its console to Selenium (Chrome and Edge do).\n";
        }
        return lines.isEmpty() ? "No console errors or warnings.\n" : String.join("\n", lines) + "\n";
    }

    /**
     * Chrome and Edge say a script that did not load as "https://x/app.js - Failed to load resource: ...".
     * Ads the suite refused (ERR_BLOCKED_BY_CLIENT) are not the page's.
     */
    private void noteFailedScript(String message) {
        int at = message.indexOf(" - Failed to load resource: ");
        if (at < 0 || message.contains("ERR_BLOCKED_BY_CLIENT")) return;
        String url = message.substring(0, at).trim();
        String path = url;
        for (char end : new char[] {'?', '#'}) if (path.indexOf(end) >= 0) path = path.substring(0, path.indexOf(end));
        if (path.endsWith(".js") || path.endsWith(".mjs")) scriptFailed(url, message.substring(at + " - Failed to load resource: ".length()).trim());
    }

    private String steps(Throwable cause) {
        StringBuilder out = new StringBuilder(displayName).append("\n\n");
        List<String> steps = StepLog.steps();
        for (int i = 0; i < steps.size(); i++) {
            out.append(i + 1).append(". ").append(steps.get(i)).append(i == steps.size() - 1 ? "   <- FAILED HERE" : "").append("\n");
        }
        out.append("\nBecause: ").append(cause).append("\n");
        String scripts = scriptNote();
        if (scripts != null) out.append(scripts.trim()).append("\n");
        try {
            out.append("URL:     ").append(driver.getCurrentUrl()).append("\n").append("Title:   ").append(driver.getTitle()).append("\n");
        } catch (RuntimeException e) {
            out.append("(the browser could not be asked for its URL and title)\n");
        }
        return out.toString();
    }

    private static void write(Path file, String text) throws IOException {
        Files.writeString(file, text, StandardCharsets.UTF_8);
    }

    /**
     * Once per run, before the first test: the last run's failures move to failures-previous/
     * (replacing the run before that). A test that passes now has no folder in failures/.
     */
    private static synchronized void startClean() {
        if (cleared) return;
        cleared = true;
        try {
            deleteAll(PREVIOUS);
            if (Files.exists(FAILURES)) Files.move(FAILURES, PREVIOUS);
        } catch (IOException e) {
            // A file held open (an editor showing a screenshot, say) can stop the move: clear instead.
            try {
                deleteAll(FAILURES);
            } catch (IOException ignored) {
                // an old folder left over is harmless
            }
        }
    }

    /** A script of the page's that did not load, and why: the first reason given for an address is kept. */
    void scriptFailed(String url, String why) {
        synchronized (failedScripts) {
            for (String seen : failedScripts) if (seen.startsWith(url + " (")) return;
            failedScripts.add(url + " (" + why + ")");
        }
    }

    /**
     * Which of the page's scripts did not load, as a line under the failure, or null: a page drawn by
     * its script stays blank without it, and then fails as "not visible", which hides the reason.
     */
    String scriptNote() {
        synchronized (failedScripts) {
            if (failedScripts.isEmpty()) return null;
            int n = failedScripts.size();
            return "   note: " + (n == 1 ? "a script of the page's" : n + " scripts of the page's") + " did not load, which can leave it blank or half drawn: "
                    + String.join("; ", failedScripts.subList(0, Math.min(3, n))) + (n > 3 ? "; and " + (n - 3) + " more (network.txt, console.txt)" : "");
        }
    }

    /** The folder a retried test's first try is saved in, inside the test's own (G-135). */
    static final String FIRST_TRY = "try-1";

    /** This evidence, saved as a retried test's first try (try-1/), which its second try's keeps. */
    Evidence firstTry() {
        tried = FIRST_TRY;
        return this;
    }

    /** Empties the folder, all but the one named. */
    private static void clearKeeping(Path dir, String keep) throws IOException {
        if (!Files.isDirectory(dir)) return;
        try (Stream<Path> inside = Files.list(dir)) {
            for (Path p : inside.toList()) if (!p.getFileName().toString().equals(keep)) deleteAll(p);
        }
    }

    static void deleteAll(Path dir) throws IOException {
        if (!Files.exists(dir)) return;
        try (Stream<Path> paths = Files.walk(dir)) {
            for (Path p : paths.sorted(Comparator.reverseOrder()).toList()) Files.delete(p);
        }
    }

    private interface Step {
        void run() throws Exception;
    }

    private static void attempt(Step step) {
        try {
            step.run();
        } catch (Exception e) {
            // saving evidence never hides the failure itself
        }
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // More this site needs saved when a test fails (the browser's local storage, say).
    // ==== END YOURS (extras) ====
}
