// Generated by Suite Builder from a crawl of the site. Click actions for HomePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Find } from '../../../core/Find';
import { StepLog } from '../../../core/StepLog';
import { UserActions } from '../../../core/UserActions';
import { AbtestPage } from '../../abtest/AbtestPage';
import { AddRemoveElementsPage } from '../../addremoveelements/AddRemoveElementsPage';
import { BrokenImagesPage } from '../../brokenimages/BrokenImagesPage';
import { ChallengingDomPage } from '../../challengingdom/ChallengingDomPage';
import { CheckboxesPage } from '../../checkboxes/CheckboxesPage';
import { ContextMenuPage } from '../../contextmenu/ContextMenuPage';
import { DisappearingElementsPage } from '../../disappearingelements/DisappearingElementsPage';
import { DownloadPage } from '../../download/DownloadPage';
import { DragAndDropPage } from '../../draganddrop/DragAndDropPage';
import { DropdownPage } from '../../dropdown/DropdownPage';
import { DynamicContentPage } from '../../dynamiccontent/DynamicContentPage';
import { DynamicControlsPage } from '../../dynamiccontrols/DynamicControlsPage';
import { DynamicLoadingPage } from '../../dynamicloading/DynamicLoadingPage';
import { EntryAdPage } from '../../entryad/EntryAdPage';
import { ExitIntentPage } from '../../exitintent/ExitIntentPage';
import { FloatingMenuPage } from '../../floatingmenu/FloatingMenuPage';
import { ForgotPasswordPage } from '../../forgotpassword/ForgotPasswordPage';
import { FramesPage } from '../../frames/FramesPage';
import { GeolocationPage } from '../../geolocation/GeolocationPage';
import { HorizontalSliderPage } from '../../horizontalslider/HorizontalSliderPage';
import { HoversPage } from '../../hovers/HoversPage';
import { InfiniteScrollPage } from '../../infinitescroll/InfiniteScrollPage';
import { InputsPage } from '../../inputs/InputsPage';
import { JavascriptAlertsPage } from '../../javascriptalerts/JavascriptAlertsPage';
import { JavascriptErrorPage } from '../../javascripterror/JavascriptErrorPage';
import { JqueryuiMenuPage } from '../../jqueryuimenu/JqueryuiMenuPage';
import { KeyPressesPage } from '../../keypresses/KeyPressesPage';
import { LargePage } from '../../large/LargePage';
import { NestedFramesPage } from '../../nestedframes/NestedFramesPage';
import { NotificationMessageRenderedPage } from '../../notificationmessagerendered/NotificationMessageRenderedPage';
import { RedirectorPage } from '../../redirector/RedirectorPage';
import { ShadowdomPage } from '../../shadowdom/ShadowdomPage';
import { ShiftingContentPage } from '../../shiftingcontent/ShiftingContentPage';
import { SlowPage } from '../../slow/SlowPage';
import { StatusCodesPage } from '../../statuscodes/StatusCodesPage';
import { TablesPage } from '../../tables/TablesPage';
import { TinymcePage } from '../../tinymce/TinymcePage';
import { TyposPage } from '../../typos/TyposPage';
import { UploadPage } from '../../upload/UploadPage';
import { WindowsPage } from '../../windows/WindowsPage';
import { HomeElements } from '../HomeElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on HomePage. Clicks that change page return the next page; others return this. */
export class HomeClickActions {
  /** Clicks the link to TinymcePage (WYSIWYG Editor) and waits for it. */
  goToTinymce(): TinymcePage {
    StepLog.step('Click "WYSIWYG Editor"');
    Find.visible(HomeElements.TINYMCE_LINK).click();
    return new TinymcePage().get();
  }

  /** Clicks the link to FramesPage (Frames) and waits for it. */
  goToFrames(): FramesPage {
    StepLog.step('Click "Frames"');
    Find.visible(HomeElements.FRAMES_LINK).click();
    return new FramesPage().get();
  }

  /** Clicks the link to DropdownPage (Dropdown) and waits for it. */
  goToDropdown(): DropdownPage {
    StepLog.step('Click "Dropdown"');
    Find.visible(HomeElements.DROPDOWN_LINK).click();
    return new DropdownPage().get();
  }

  /** Clicks the link to NotificationMessageRenderedPage (Notification Messages) and waits for it. */
  goToNotificationMessageRendered(): NotificationMessageRenderedPage {
    StepLog.step('Click "Notification Messages"');
    Find.visible(HomeElements.NOTIFICATION_MESSAGE_RENDERED_LINK).click();
    return new NotificationMessageRenderedPage().get();
  }

  /** Clicks the link to ChallengingDomPage (Challenging DOM) and waits for it. */
  goToChallengingDom(): ChallengingDomPage {
    StepLog.step('Click "Challenging DOM"');
    Find.visible(HomeElements.CHALLENGING_DOM_LINK).click();
    return new ChallengingDomPage().get();
  }

  /** Clicks the link to JavascriptAlertsPage (JavaScript Alerts) and waits for it. */
  goToJavascriptAlerts(): JavascriptAlertsPage {
    StepLog.step('Click "JavaScript Alerts"');
    Find.visible(HomeElements.JAVASCRIPT_ALERTS_LINK).click();
    return new JavascriptAlertsPage().get();
  }

  /** Clicks the link to ExitIntentPage (Exit Intent) and waits for it. */
  goToExitIntent(): ExitIntentPage {
    StepLog.step('Click "Exit Intent"');
    Find.visible(HomeElements.EXIT_INTENT_LINK).click();
    return new ExitIntentPage().get();
  }

  /** Clicks the link to JqueryuiMenuPage (JQuery UI Menus) and waits for it. */
  goToJqueryuiMenu(): JqueryuiMenuPage {
    StepLog.step('Click "JQuery UI Menus"');
    Find.visible(HomeElements.JQUERYUI_MENU_LINK).click();
    return new JqueryuiMenuPage().get();
  }

  /** Clicks the link to TablesPage (Sortable Data Tables) and waits for it. */
  goToTables(): TablesPage {
    StepLog.step('Click "Sortable Data Tables"');
    Find.visible(HomeElements.TABLES_LINK).click();
    return new TablesPage().get();
  }

  /** Clicks the link to InfiniteScrollPage (Infinite Scroll) and waits for it. */
  goToInfiniteScroll(): InfiniteScrollPage {
    StepLog.step('Click "Infinite Scroll"');
    Find.visible(HomeElements.INFINITE_SCROLL_LINK).click();
    return new InfiniteScrollPage().get();
  }

  /** Clicks the link to DynamicLoadingPage (Dynamic Loading) and waits for it. */
  goToDynamicLoading(): DynamicLoadingPage {
    StepLog.step('Click "Dynamic Loading"');
    Find.visible(HomeElements.DYNAMIC_LOADING_LINK).click();
    return new DynamicLoadingPage().get();
  }

  /** Clicks the link to ShadowdomPage (Shadow DOM) and waits for it. */
  goToShadowdom(): ShadowdomPage {
    StepLog.step('Click "Shadow DOM"');
    Find.visible(HomeElements.SHADOWDOM_LINK).click();
    return new ShadowdomPage().get();
  }

  /** Clicks the link to DisappearingElementsPage (Disappearing Elements) and waits for it. */
  goToDisappearingElements(): DisappearingElementsPage {
    StepLog.step('Click "Disappearing Elements"');
    Find.visible(HomeElements.DISAPPEARING_ELEMENTS_LINK).click();
    return new DisappearingElementsPage().get();
  }

  /** Clicks the link to RedirectorPage (Redirect Link) and waits for it. */
  goToRedirector(): RedirectorPage {
    StepLog.step('Click "Redirect Link"');
    Find.visible(HomeElements.REDIRECTOR_LINK).click();
    return new RedirectorPage().get();
  }

  /** Clicks the link to GeolocationPage (Geolocation) and waits for it. */
  goToGeolocation(): GeolocationPage {
    StepLog.step('Click "Geolocation"');
    Find.visible(HomeElements.GEOLOCATION_LINK).click();
    return new GeolocationPage().get();
  }

  /** Clicks the link to AddRemoveElementsPage (Add/Remove Elements) and waits for it. */
  goToAddRemoveElements(): AddRemoveElementsPage {
    StepLog.step('Click "Add/Remove Elements"');
    Find.visible(HomeElements.ADD_REMOVE_ELEMENTS_LINK).click();
    return new AddRemoveElementsPage().get();
  }

  /** Clicks the link to JavascriptErrorPage (JavaScript onload event error) and waits for it. */
  goToJavascriptError(): JavascriptErrorPage {
    StepLog.step('Click "JavaScript onload event error"');
    Find.visible(HomeElements.JAVASCRIPT_ERROR_LINK).click();
    return new JavascriptErrorPage().get();
  }

  /** Clicks the link to EntryAdPage (Entry Ad) and waits for it. */
  goToEntryAd(): EntryAdPage {
    StepLog.step('Click "Entry Ad"');
    Find.visible(HomeElements.ENTRY_AD_LINK).click();
    return new EntryAdPage().get();
  }

  /** Clicks the link to StatusCodesPage (Status Codes) and waits for it. */
  goToStatusCodes(): StatusCodesPage {
    StepLog.step('Click "Status Codes"');
    Find.visible(HomeElements.STATUS_CODES_LINK).click();
    return new StatusCodesPage().get();
  }

  /** Clicks the link to NestedFramesPage (Nested Frames) and waits for it. */
  goToNestedFrames(): NestedFramesPage {
    StepLog.step('Click "Nested Frames"');
    Find.visible(HomeElements.NESTED_FRAMES_LINK).click();
    return new NestedFramesPage().get();
  }

  /** Clicks the link to ForgotPasswordPage (Forgot Password) and waits for it. */
  goToForgotPassword(): ForgotPasswordPage {
    StepLog.step('Click "Forgot Password"');
    Find.visible(HomeElements.FORGOT_PASSWORD_LINK).click();
    return new ForgotPasswordPage().get();
  }

  /** Clicks the link to CheckboxesPage (Checkboxes) and waits for it. */
  goToCheckboxes(): CheckboxesPage {
    StepLog.step('Click "Checkboxes"');
    Find.visible(HomeElements.CHECKBOXES_LINK).click();
    return new CheckboxesPage().get();
  }

  /** Clicks the link to LargePage (Large & Deep DOM) and waits for it. */
  goToLarge(): LargePage {
    StepLog.step('Click "Large & Deep DOM"');
    Find.visible(HomeElements.LARGE_LINK).click();
    return new LargePage().get();
  }

  /** Clicks the link to UploadPage (File Upload) and waits for it. */
  goToUpload(): UploadPage {
    StepLog.step('Click "File Upload"');
    Find.visible(HomeElements.UPLOAD_LINK).click();
    return new UploadPage().get();
  }

  /** Clicks the link to DynamicContentPage (Dynamic Content) and waits for it. */
  goToDynamicContent(): DynamicContentPage {
    StepLog.step('Click "Dynamic Content"');
    Find.visible(HomeElements.DYNAMIC_CONTENT_LINK).click();
    return new DynamicContentPage().get();
  }

  /** Clicks the link to ShiftingContentPage (Shifting Content) and waits for it. */
  goToShiftingContent(): ShiftingContentPage {
    StepLog.step('Click "Shifting Content"');
    Find.visible(HomeElements.SHIFTING_CONTENT_LINK).click();
    return new ShiftingContentPage().get();
  }

  /** Clicks the link to HoversPage (Hovers) and waits for it. */
  goToHovers(): HoversPage {
    StepLog.step('Click "Hovers"');
    Find.visible(HomeElements.HOVERS_LINK).click();
    return new HoversPage().get();
  }

  /** Clicks the link to AbtestPage (A/B Testing) and waits for it. */
  goToAbtest(): AbtestPage {
    StepLog.step('Click "A/B Testing"');
    Find.visible(HomeElements.ABTEST_LINK).click();
    return new AbtestPage().get();
  }

  /** Clicks the link to KeyPressesPage (Key Presses) and waits for it. */
  goToKeyPresses(): KeyPressesPage {
    StepLog.step('Click "Key Presses"');
    Find.visible(HomeElements.KEY_PRESSES_LINK).click();
    return new KeyPressesPage().get();
  }

  /** Clicks the link to DynamicControlsPage (Dynamic Controls) and waits for it. */
  goToDynamicControls(): DynamicControlsPage {
    StepLog.step('Click "Dynamic Controls"');
    Find.visible(HomeElements.DYNAMIC_CONTROLS_LINK).click();
    return new DynamicControlsPage().get();
  }

  /** Clicks the link to TyposPage (Typos) and waits for it. */
  goToTypos(): TyposPage {
    StepLog.step('Click "Typos"');
    Find.visible(HomeElements.TYPOS_LINK).click();
    return new TyposPage().get();
  }

  /** Clicks the link to ContextMenuPage (Context Menu) and waits for it. */
  goToContextMenu(): ContextMenuPage {
    StepLog.step('Click "Context Menu"');
    Find.visible(HomeElements.CONTEXT_MENU_LINK).click();
    return new ContextMenuPage().get();
  }

  /** Clicks the link to HorizontalSliderPage (Horizontal Slider) and waits for it. */
  goToHorizontalSlider(): HorizontalSliderPage {
    StepLog.step('Click "Horizontal Slider"');
    Find.visible(HomeElements.HORIZONTAL_SLIDER_LINK).click();
    return new HorizontalSliderPage().get();
  }

  /** Clicks the link to BrokenImagesPage (Broken Images) and waits for it. */
  goToBrokenImages(): BrokenImagesPage {
    StepLog.step('Click "Broken Images"');
    Find.visible(HomeElements.BROKEN_IMAGES_LINK).click();
    return new BrokenImagesPage().get();
  }

  /** Clicks the link to WindowsPage (Multiple Windows) and waits for it. */
  goToWindows(): WindowsPage {
    StepLog.step('Click "Multiple Windows"');
    Find.visible(HomeElements.WINDOWS_LINK).click();
    return new WindowsPage().get();
  }

  /** Clicks the link to FloatingMenuPage (Floating Menu) and waits for it. */
  goToFloatingMenu(): FloatingMenuPage {
    StepLog.step('Click "Floating Menu"');
    Find.visible(HomeElements.FLOATING_MENU_LINK).click();
    return new FloatingMenuPage().get();
  }

  /** Clicks the link to DownloadPage (File Download) and waits for it. */
  goToDownload(): DownloadPage {
    StepLog.step('Click "File Download"');
    Find.visible(HomeElements.DOWNLOAD_LINK).click();
    return new DownloadPage().get();
  }

  /** Clicks the link to SlowPage (Slow Resources) and waits for it. */
  goToSlow(): SlowPage {
    StepLog.step('Click "Slow Resources"');
    Find.visible(HomeElements.SLOW_LINK).click();
    return new SlowPage().get();
  }

  /** Clicks the link to InputsPage (Inputs) and waits for it. */
  goToInputs(): InputsPage {
    StepLog.step('Click "Inputs"');
    Find.visible(HomeElements.INPUTS_LINK).click();
    return new InputsPage().get();
  }

  /** Clicks the link to DragAndDropPage (Drag and Drop) and waits for it. */
  goToDragAndDrop(): DragAndDropPage {
    StepLog.step('Click "Drag and Drop"');
    Find.visible(HomeElements.DRAG_AND_DROP_LINK).click();
    return new DragAndDropPage().get();
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
  // acceptTerms(): HomeClickActions {
  //   UserActions.click(HomeElements.ACCEPT_BUTTON);
  //   return this;
  // }
  // ==== END YOURS (actions) ====
}
