// Generated by Suite Builder from a crawl of the site. Tasks for KeyPressesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.keypresses;

import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on KeyPressesPage, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
public class KeyPressesTasks {
    private final Page page;

    public KeyPressesTasks(Page page) {
        this.page = page;
    }

    /**
     * Fills the "Key Presses" form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). Its values: {@code KeyPresses.sample()},
     * or a copy with one changed, {@code KeyPresses.sample().withTextField("...")}.
     */
    public KeyPressesPage fillKeyPressesForm(KeyPresses form) {
        KeyPressesPage here = new KeyPressesPage(page);
        here.enter().textField(form.textField());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillKeyPressesForm(KeyPresses.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public KeyPressesPage fillKeyPressesForm(String textField) {
        return fillKeyPressesForm(new KeyPresses(textField));
    }

    // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
    // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
    // public ThankYouPage signUp(String email) {
    //     KeyPressesPage here = new KeyPressesPage(page);
    //     here.enter().email(email);
    //     here.check().terms();
    //     return here.click().submit();
    // }
    // ==== END YOURS (tasks) ====
}
