// Generated by Suite Builder from a crawl of the site. The "Key Presses" form on KeyPressesPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what KeyPressesTasks.fillKeyPressesForm takes.
package com.herokuapp.theinternet.tests.pages.keypresses;

import com.herokuapp.theinternet.tests.core.SiteConfig;

/**
 * The "Key Presses" form on KeyPressesPage, as one value: its fields in page order, what
 * {@link KeyPressesTasks#fillKeyPressesForm(KeyPresses)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code KeyPresses.sample().withTextField("...")}.
 */
public record KeyPresses(String textField) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DtextField=...) or in suite.properties, by its name.
     */
    public static KeyPresses sample() {
        return new KeyPresses(
                SiteConfig.value("textField", "Test textField"));
    }

    /** This KeyPresses with textField in place of its own. */
    public KeyPresses withTextField(String textField) {
        return new KeyPresses(textField);
    }
}
