// Generated by Suite Builder from a crawl of the site. Click actions for StatusCodesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.statuscodesdetail.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.statuscodes.StatusCodesPage;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.StatusCodesDetailElements;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on StatusCodesDetailPage. Clicks that change page return the next page; others return this. */
public class StatusCodesDetailClickActions {
    private final WebDriver driver;

    public StatusCodesDetailClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks the link to StatusCodesPage (here) and waits for it. */
    public StatusCodesPage goToStatusCodes() {
        UserActions.click(driver, StatusCodesDetailElements.STATUS_CODES_LINK);
        return new StatusCodesPage(driver).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public StatusCodesDetailVerifyActions verify() {
        return new StatusCodesDetailVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public StatusCodesDetailClickActions acceptTerms() {
    //     UserActions.click(driver, StatusCodesDetailElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
