// Generated by Suite Builder from a crawl of the site. Checks for HomePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.home.actions;

import com.herokuapp.theinternet.tests.pages.home.HomePage;
import com.herokuapp.theinternet.tests.pages.home.HomeElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on HomePage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class HomeVerifyActions {
    private final WebDriver driver;

    public HomeVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public HomeVerifyActions isLoaded() {
        HomePage here = new HomePage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public HomeVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Welcome to the-internet\", \"Available Examples\")",
                HomeElements.WELCOME_TO_THE_INTERNET_HEADING, HomeElements.AVAILABLE_EXAMPLES_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(HomeElements.SOME_HEADING)}. */
    public HomeVerifyActions shows(HomeElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public HomeVerifyActions doesNotShow(HomeElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public HomeVerifyActions says(HomeElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public HomeVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public HomeVerifyActions holds(HomeElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public HomeVerifyActions isEmpty(HomeElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public HomeVerifyActions refusesEmpty(HomeElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public HomeVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, HomeElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
