// Generated by Suite Builder from a crawl of the site. Click actions for JavascriptAlertsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.javascriptalerts.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.javascriptalerts.JavascriptAlertsElements;
import com.herokuapp.theinternet.tests.pages.javascriptalerts.JavascriptAlertsPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on JavascriptAlertsPage. Clicks that change page return the next page; others return this. */
public class JavascriptAlertsClickActions {
    private final WebDriver driver;

    public JavascriptAlertsClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks the button "Click for JS Alert". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public JavascriptAlertsPage clickForJsAlert() {
        UserActions.click(driver, JavascriptAlertsElements.CLICK_FOR_JS_ALERT_BUTTON);
        return new JavascriptAlertsPage(driver);
    }

    /** Clicks the button "Click for JS Confirm". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public JavascriptAlertsPage clickForJsConfirm() {
        UserActions.click(driver, JavascriptAlertsElements.CLICK_FOR_JS_CONFIRM_BUTTON);
        return new JavascriptAlertsPage(driver);
    }

    /** Clicks the button "Click for JS Prompt". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public JavascriptAlertsPage clickForJsPrompt() {
        UserActions.click(driver, JavascriptAlertsElements.CLICK_FOR_JS_PROMPT_BUTTON);
        return new JavascriptAlertsPage(driver);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public JavascriptAlertsVerifyActions verify() {
        return new JavascriptAlertsVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public JavascriptAlertsClickActions acceptTerms() {
    //     UserActions.click(driver, JavascriptAlertsElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
