// Generated by Suite Builder from a crawl of the site. Locators for InfiniteScrollDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings, literal } from '../../core/Headings';
import { byXPath, element, elements, type PageElement } from '../../core/PageElement';
import { UrlPaths } from '../../uri/UrlPaths';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 34 pages like /infinite_scroll/18, /infinite_scroll/19, /infinite_scroll/20.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const InfiniteScrollDetailElements = elements({
  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

/** A link to InfiniteScrollDetailPage, e.g. /infinite_scroll/19. */
export function getInfiniteScrollDetailLink(name: string): PageElement {
  const href = '/infinite_scroll/' + name;
  // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
  return element('INFINITE_SCROLL_DETAIL_LINK', byXPath(`//a[@href=${literal(href)} or @href=${literal(UrlPaths.decoded(href))}]`), `the link to ${href}`);
}

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
