// Generated by Suite Builder from a crawl of the site. Page object for JavascriptAlertsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.javascriptalerts;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.ClickableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.javascriptalerts.actions.JavascriptAlertsClickActions;
import com.herokuapp.theinternet.tests.pages.javascriptalerts.actions.JavascriptAlertsReadActions;
import com.herokuapp.theinternet.tests.pages.javascriptalerts.actions.JavascriptAlertsVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /javascript_alerts.
 * Stories call it:  "JavaScript Alerts" (the links that lead here).
 * Get here:         new JavascriptAlertsPage(page).open()
 *                   from HomePage: click().goToJavascriptAlerts()
 * The crawl saw:    1 page of this type (/javascript_alerts); it showed "JavaScript Alerts".
 * Proven loaded by: the heading "JavaScript Alerts" (isLoaded(), PROVES_LOADED: what a copy edit
 *                   leaves alone first).
 * As crawled:       crawl/pages/javascript_alerts.html (the page's HTML when crawled: check a
 *                   locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/JavascriptAlertsPage/
 *                   (saved-pages/README.md) and add what it shows to JavascriptAlertsElements.
 * </pre>
 */
public class JavascriptAlertsPage extends LoadablePage<JavascriptAlertsPage> implements
        ClickableAction<JavascriptAlertsClickActions>,
        ReadableAction<JavascriptAlertsReadActions>,
        VerifiableAction<JavascriptAlertsVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "The Internet";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default ca4f57bd
    static final List<JavascriptAlertsElements> PROVES_LOADED = List.of(
            JavascriptAlertsElements.JAVA_SCRIPT_ALERTS_HEADING);
    // ==== END YOURS (load-proof) ====

    public JavascriptAlertsPage(Page page) {
        super(page);
    }

    /** Goes to /javascript_alerts and waits until it has fully loaded. */
    public JavascriptAlertsPage open() {
        navigate(UrlPaths.JAVASCRIPT_ALERTS);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.JAVASCRIPT_ALERTS);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.JAVASCRIPT_ALERTS);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (JavascriptAlertsElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, JavascriptAlertsElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public JavascriptAlertsClickActions click() {
        return new JavascriptAlertsClickActions(page);
    }

    @Override
    public JavascriptAlertsReadActions read() {
        return new JavascriptAlertsReadActions(page);
    }

    @Override
    public JavascriptAlertsVerifyActions verify() {
        return new JavascriptAlertsVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
