// Generated by Suite Builder from a crawl of the site. Checks for DropdownPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dropdown.actions;

import com.herokuapp.theinternet.tests.pages.dropdown.DropdownPage;
import com.herokuapp.theinternet.tests.pages.dropdown.DropdownElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on DropdownPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class DropdownVerifyActions {
    private final WebDriver driver;

    public DropdownVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public DropdownVerifyActions isLoaded() {
        DropdownPage here = new DropdownPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public DropdownVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Dropdown List\")",
                DropdownElements.DROPDOWN_LIST_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(DropdownElements.SOME_HEADING)}. */
    public DropdownVerifyActions shows(DropdownElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public DropdownVerifyActions doesNotShow(DropdownElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public DropdownVerifyActions says(DropdownElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public DropdownVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public DropdownVerifyActions holds(DropdownElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public DropdownVerifyActions isEmpty(DropdownElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public DropdownVerifyActions refusesEmpty(DropdownElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public DropdownVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, DropdownElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
