// Generated by Suite Builder from a crawl of the site. Checks for AbtestPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Checks } from '../../../core/Checks';
import { type PageElement } from '../../../core/PageElement';
import { StepLog } from '../../../core/StepLog';
import { AbtestElements } from '../AbtestElements';
import { AbtestPage } from '../AbtestPage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on AbtestPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
export class AbtestVerifyActions {
  /** The page has fully loaded: URL, page load, title and key elements. */
  isLoaded(): AbtestVerifyActions {
    const here = new AbtestPage();
    StepLog.step(`Check that ${here.describe()} has fully loaded`);
    here.get();
    return this;
  }

  /** Every section heading this page type shares is visible. */
  sectionHeadingsVisible(): AbtestVerifyActions {
    Checks.allShown('its section headings ("A/B Test Variation 1")', AbtestElements.A_B_TEST_VARIATION_1_HEADING);
    return this;
  }

  /** The element is shown, e.g. verify().shows(AbtestElements.SOME_HEADING). */
  shows(element: PageElement): AbtestVerifyActions {
    Checks.isShown(element);
    return this;
  }

  /** The element is not shown (gone, or hidden). */
  doesNotShow(element: PageElement): AbtestVerifyActions {
    Checks.isNotShown(element);
    return this;
  }

  /** The element says exactly this (whatever the spacing). */
  says(element: PageElement, text: string): AbtestVerifyActions {
    Checks.hasText(element, text);
    return this;
  }

  /** The page shows this text somewhere a visitor can see it. */
  showsText(text: string): AbtestVerifyActions {
    Checks.pageShowsText(text);
    return this;
  }

  /** The field holds exactly this: what was typed into it. */
  holds(element: PageElement, text: string): AbtestVerifyActions {
    Checks.hasValue(element, text);
    return this;
  }

  /** The field is empty. */
  isEmpty(element: PageElement): AbtestVerifyActions {
    Checks.hasValue(element, '');
    return this;
  }

  /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
  refusesEmpty(element: PageElement): AbtestVerifyActions {
    Checks.refusesEmpty(element);
    return this;
  }

  // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
  // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
  // showsOrderConfirmation(): AbtestVerifyActions {
  //   Checks.isShown(AbtestElements.CONFIRMATION_HEADING);
  //   return this;
  // }
  // ==== END YOURS (checks) ====
}
