// Generated by Suite Builder from a crawl of the site. Locators for JqueryuiMenuPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings } from '../../core/Headings';
import { byXPath, elements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /jqueryui/menu.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const JqueryuiMenuElements = elements({
  // Section headings the crawled pages of this type share. One a test does not use is harmless.
  /** Heading "JQueryUI - Menu": every crawled page of this type showed it. */
  JQUERY_UI_MENU_HEADING: Headings.named('JQueryUI - Menu'),

  // Links to other pages (from the crawl).
  /** Link "Back to JQuery UI" (href /jqueryui) to JqueryuiPage, seen by the crawl on /jqueryui/menu. */
  JQUERYUI_LINK: byXPath('//a[@href=\'/jqueryui\']'),

  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
