// Generated by Suite Builder from a crawl of the site. Click actions for AddRemoveElementsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Find } from '../../../core/Find';
import { StepLog } from '../../../core/StepLog';
import { UserActions } from '../../../core/UserActions';
import { AddRemoveElementsElements } from '../AddRemoveElementsElements';
import { AddRemoveElementsPage } from '../AddRemoveElementsPage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on AddRemoveElementsPage. Clicks that change page return the next page; others return this. */
export class AddRemoveElementsClickActions {
  /** Clicks the button "Add Element". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
  addElement(): AddRemoveElementsPage {
    UserActions.click(AddRemoveElementsElements.ADD_ELEMENT_BUTTON);
    return new AddRemoveElementsPage();
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
  // acceptTerms(): AddRemoveElementsClickActions {
  //   UserActions.click(AddRemoveElementsElements.ACCEPT_BUTTON);
  //   return this;
  // }
  // ==== END YOURS (actions) ====
}
