// Generated by Suite Builder from a crawl of the site. Page object for UploadPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { UploadElements } from './UploadElements';
import { UploadClickActions } from './actions/UploadClickActions';
import { UploadEnterActions } from './actions/UploadEnterActions';
import { UploadReadActions } from './actions/UploadReadActions';
import { UploadVerifyActions } from './actions/UploadVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /upload.
 * Stories call it:  "File Upload" (the links that lead here).
 * Get here:         new UploadPage().open()
 *                   from HomePage: click().goToUpload()
 * The crawl saw:    1 page of this type (/upload); it showed "File Uploader".
 * Proven loaded by: the heading "File Uploader" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * Has a form:       on 1 of 1. Sending it on the live site sends real data: read ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/upload.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/UploadPage/ and add what it shows to UploadElements.
 */
export class UploadPage extends LoadablePage<UploadPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default a4cd1d4d
  static readonly PROVES_LOADED: readonly PageElement[] = [
    UploadElements.FILE_UPLOADER_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('UploadPage');
  }

  /** Goes to /upload and waits until it has fully loaded. */
  open(): UploadPage {
    this.navigate(UrlPaths.UPLOAD);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.UPLOAD, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.UPLOAD}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(UploadPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${UploadPage.TITLE}"`);
    for (const element of UploadPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(UploadElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  click(): UploadClickActions {
    return new UploadClickActions();
  }

  enter(): UploadEnterActions {
    return new UploadEnterActions();
  }

  read(): UploadReadActions {
    return new UploadReadActions();
  }

  verify(): UploadVerifyActions {
    return new UploadVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
