// Generated by Suite Builder from a crawl of the site. Checks for InfiniteScrollPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.infinitescroll.actions;

import com.herokuapp.theinternet.tests.pages.infinitescroll.InfiniteScrollPage;
import com.herokuapp.theinternet.tests.pages.infinitescroll.InfiniteScrollElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on InfiniteScrollPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class InfiniteScrollVerifyActions {
    private final WebDriver driver;

    public InfiniteScrollVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public InfiniteScrollVerifyActions isLoaded() {
        InfiniteScrollPage here = new InfiniteScrollPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public InfiniteScrollVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Infinite Scroll\")",
                InfiniteScrollElements.INFINITE_SCROLL_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(InfiniteScrollElements.SOME_HEADING)}. */
    public InfiniteScrollVerifyActions shows(InfiniteScrollElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public InfiniteScrollVerifyActions doesNotShow(InfiniteScrollElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public InfiniteScrollVerifyActions says(InfiniteScrollElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public InfiniteScrollVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public InfiniteScrollVerifyActions holds(InfiniteScrollElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public InfiniteScrollVerifyActions isEmpty(InfiniteScrollElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public InfiniteScrollVerifyActions refusesEmpty(InfiniteScrollElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public InfiniteScrollVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, InfiniteScrollElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
