// Generated by Suite Builder from a crawl of the site. Click actions for InfiniteScrollPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.infinitescroll.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.infinitescroll.InfiniteScrollElements;
import com.herokuapp.theinternet.tests.pages.infinitescrolldetail.InfiniteScrollDetailPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on InfiniteScrollPage. Clicks that change page return the next page; others return this. */
public class InfiniteScrollClickActions {
    private final WebDriver driver;

    public InfiniteScrollClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks a link to InfiniteScrollDetailPage (e.g. next page) and waits for it. */
    public InfiniteScrollDetailPage goToInfiniteScrollDetail(String name) {
        UserActions.click(driver, InfiniteScrollElements.getInfiniteScrollDetailLink(name));
        return new InfiniteScrollDetailPage(driver).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public InfiniteScrollVerifyActions verify() {
        return new InfiniteScrollVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public InfiniteScrollClickActions acceptTerms() {
    //     UserActions.click(driver, InfiniteScrollElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
