// Generated by Suite Builder from a crawl of the site. Click actions for StatusCodesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.statuscodes.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.statuscodes.StatusCodesElements;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.StatusCodesDetailPage;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on StatusCodesPage. Clicks that change page return the next page; others return this. */
public class StatusCodesClickActions {
    private final Page page;

    public StatusCodesClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to StatusCodesDetailPage (e.g. 200) and waits for it. */
    public StatusCodesDetailPage goToStatusCodesDetail(String name) {
        UserActions.click(page, StatusCodesElements.getStatusCodesDetailLink(name));
        return new StatusCodesDetailPage(page).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public StatusCodesVerifyActions verify() {
        return new StatusCodesVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public StatusCodesClickActions acceptTerms() {
    //     UserActions.click(page, StatusCodesElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
