// Generated by Suite Builder from a crawl of the site. Page object for AddRemoveElementsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { AddRemoveElementsElements } from './AddRemoveElementsElements';
import { AddRemoveElementsClickActions } from './actions/AddRemoveElementsClickActions';
import { AddRemoveElementsReadActions } from './actions/AddRemoveElementsReadActions';
import { AddRemoveElementsVerifyActions } from './actions/AddRemoveElementsVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /add_remove_elements/.
 * Stories call it:  "Add/Remove Elements" (the links that lead here).
 * Get here:         new AddRemoveElementsPage().open()
 *                   from HomePage: click().goToAddRemoveElements()
 * The crawl saw:    1 page of this type (/add_remove_elements/); it showed "Add/Remove Elements".
 * Proven loaded by: the heading "Add/Remove Elements" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/add_remove_elements.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/AddRemoveElementsPage/ and add what it shows to AddRemoveElementsElements.
 */
export class AddRemoveElementsPage extends LoadablePage<AddRemoveElementsPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default deea8541
  static readonly PROVES_LOADED: readonly PageElement[] = [
    AddRemoveElementsElements.ADD_REMOVE_ELEMENTS_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('AddRemoveElementsPage');
  }

  /** Goes to /add_remove_elements/ and waits until it has fully loaded. */
  open(): AddRemoveElementsPage {
    this.navigate(UrlPaths.ADD_REMOVE_ELEMENTS);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.ADD_REMOVE_ELEMENTS, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.ADD_REMOVE_ELEMENTS}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(AddRemoveElementsPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${AddRemoveElementsPage.TITLE}"`);
    for (const element of AddRemoveElementsPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(AddRemoveElementsElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  click(): AddRemoveElementsClickActions {
    return new AddRemoveElementsClickActions();
  }

  read(): AddRemoveElementsReadActions {
    return new AddRemoveElementsReadActions();
  }

  verify(): AddRemoveElementsVerifyActions {
    return new AddRemoveElementsVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
