// Generated by Suite Builder from a crawl of the site. Checks for TinymcePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Checks } from '../../../core/Checks';
import { type PageElement } from '../../../core/PageElement';
import { StepLog } from '../../../core/StepLog';
import { TinymceElements } from '../TinymceElements';
import { TinymcePage } from '../TinymcePage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on TinymcePage. Each one is a step of the test, and fails saying what it expected, in plain English. */
export class TinymceVerifyActions {
  /** The page has fully loaded: URL, page load, title and key elements. */
  isLoaded(): TinymceVerifyActions {
    const here = new TinymcePage();
    StepLog.step(`Check that ${here.describe()} has fully loaded`);
    here.get();
    return this;
  }

  /** Every section heading this page type shares is visible. */
  sectionHeadingsVisible(): TinymceVerifyActions {
    Checks.allShown('its section headings ("An iFrame containing the TinyMCE WYSIWYG Editor")', TinymceElements.AN_I_FRAME_CONTAINING_THE_TINY_MCE_WYSIWYG_EDITOR_HEADING);
    return this;
  }

  /** The element is shown, e.g. verify().shows(TinymceElements.SOME_HEADING). */
  shows(element: PageElement): TinymceVerifyActions {
    Checks.isShown(element);
    return this;
  }

  /** The element is not shown (gone, or hidden). */
  doesNotShow(element: PageElement): TinymceVerifyActions {
    Checks.isNotShown(element);
    return this;
  }

  /** The element says exactly this (whatever the spacing). */
  says(element: PageElement, text: string): TinymceVerifyActions {
    Checks.hasText(element, text);
    return this;
  }

  /** The page shows this text somewhere a visitor can see it. */
  showsText(text: string): TinymceVerifyActions {
    Checks.pageShowsText(text);
    return this;
  }

  /** The field holds exactly this: what was typed into it. */
  holds(element: PageElement, text: string): TinymceVerifyActions {
    Checks.hasValue(element, text);
    return this;
  }

  /** The field is empty. */
  isEmpty(element: PageElement): TinymceVerifyActions {
    Checks.hasValue(element, '');
    return this;
  }

  /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
  refusesEmpty(element: PageElement): TinymceVerifyActions {
    Checks.refusesEmpty(element);
    return this;
  }

  // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
  // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
  // showsOrderConfirmation(): TinymceVerifyActions {
  //   Checks.isShown(TinymceElements.CONFIRMATION_HEADING);
  //   return this;
  // }
  // ==== END YOURS (checks) ====
}
