// Generated by Suite Builder from a crawl of the site. EnterActions for DynamicControlsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamiccontrols.actions;

import com.herokuapp.theinternet.tests.core.SiteConfig;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.dynamiccontrols.DynamicControlsElements;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on DynamicControlsPage.
 * The crawl's own are below; add more (elements to DynamicControlsElements, then methods here) in the YOURS block.
 */
public class DynamicControlsEnterActions {
    private final Page page;

    public DynamicControlsEnterActions(Page page) {
        this.page = page;
    }

    /** Types into the text field "TEXT_FIELD_INPUT". */
    public DynamicControlsEnterActions textField(String text) {
        UserActions.type(page, DynamicControlsElements.TEXT_FIELD_INPUT, text);
        return this;
    }

    /** Empties the text field "TEXT_FIELD_INPUT". */
    public DynamicControlsEnterActions clearTextField() {
        UserActions.clear(page, DynamicControlsElements.TEXT_FIELD_INPUT);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public DynamicControlsVerifyActions verify() {
        return new DynamicControlsVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per field, e.g.:
    // public DynamicControlsEnterActions email(String text) {
    //     UserActions.type(page, DynamicControlsElements.EMAIL_INPUT, text);
    //     return this;
    // }
    // A password or other secret: UserActions.typeSecret(page, DynamicControlsElements.PASSWORD_INPUT, SiteConfig.secret("password"));
    // A dropdown: UserActions.choose(page, DynamicControlsElements.COUNTRY_SELECT, country);
    // ==== END YOURS (actions) ====
}
