@echo off
rem Generated by Suite Builder. EDIT RULES: do not edit this file; regenerating replaces all of it. The menu is menu/menu.mjs; your own commands go in a file of your own.
rem Typed in this folder, "suite" opens the suite's menu (crew, help, suite and ask all do).
where node >nul 2>&1
if errorlevel 1 (
  echo This needs Node.js: install it from https://nodejs.org, then try again. The tests run without it: see README.md.
  exit /b 1
)
node "%~dp0menu\menu.mjs" suite %*
