// Generated by Suite Builder from a crawl of the site. Page object for NestedFramesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.nestedframes;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.nestedframes.actions.NestedFramesReadActions;
import com.herokuapp.theinternet.tests.pages.nestedframes.actions.NestedFramesVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /nested_frames.
 * Stories call it:  "Nested Frames" (the links that lead here).
 * Get here:         new NestedFramesPage(driver).open()
 *                   from HomePage: click().goToNestedFrames()
 *                   from FramesPage: click().goToNestedFrames()
 * The crawl saw:    1 page of this type (/nested_frames).
 * Proven loaded by: its address and title only: add a key element to PROVES_LOADED.
 * As crawled:       crawl/pages/nested_frames.html (the page's HTML when crawled: check a locator
 *                   there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/NestedFramesPage/
 *                   (saved-pages/README.md) and add what it shows to NestedFramesElements.
 * </pre>
 */
public class NestedFramesPage extends LoadablePage<NestedFramesPage> implements
        ReadableAction<NestedFramesReadActions>,
        VerifiableAction<NestedFramesVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had no heading or structure in common, so add a key element here. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default af18f396
    static final List<NestedFramesElements> PROVES_LOADED = List.of();
    // ==== END YOURS (load-proof) ====

    public NestedFramesPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to /nested_frames and waits until it has fully loaded. */
    public NestedFramesPage open() {
        navigate(UrlPaths.NESTED_FRAMES);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(driver, UrlPaths.NESTED_FRAMES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + UrlPaths.NESTED_FRAMES);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);


        for (NestedFramesElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, NestedFramesElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public NestedFramesReadActions read() {
        return new NestedFramesReadActions(driver);
    }

    @Override
    public NestedFramesVerifyActions verify() {
        return new NestedFramesVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
