// Generated by Suite Builder from a crawl of the site. Checks for BrokenImagesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.brokenimages.actions;

import com.herokuapp.theinternet.tests.pages.brokenimages.BrokenImagesPage;
import com.herokuapp.theinternet.tests.pages.brokenimages.BrokenImagesElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on BrokenImagesPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class BrokenImagesVerifyActions {
    private final Page page;

    public BrokenImagesVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public BrokenImagesVerifyActions isLoaded() {
        BrokenImagesPage here = new BrokenImagesPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public BrokenImagesVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Broken Images\")",
                BrokenImagesElements.BROKEN_IMAGES_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(BrokenImagesElements.SOME_HEADING)}. */
    public BrokenImagesVerifyActions shows(BrokenImagesElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public BrokenImagesVerifyActions doesNotShow(BrokenImagesElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public BrokenImagesVerifyActions says(BrokenImagesElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public BrokenImagesVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public BrokenImagesVerifyActions holds(BrokenImagesElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public BrokenImagesVerifyActions isEmpty(BrokenImagesElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public BrokenImagesVerifyActions refusesEmpty(BrokenImagesElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public BrokenImagesVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, BrokenImagesElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
