// Generated by Suite Builder from a crawl of the site. Checks for HoversPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.hovers.actions;

import com.herokuapp.theinternet.tests.pages.hovers.HoversPage;
import com.herokuapp.theinternet.tests.pages.hovers.HoversElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on HoversPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class HoversVerifyActions {
    private final Page page;

    public HoversVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public HoversVerifyActions isLoaded() {
        HoversPage here = new HoversPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public HoversVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Hovers\")",
                HoversElements.HOVERS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(HoversElements.SOME_HEADING)}. */
    public HoversVerifyActions shows(HoversElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public HoversVerifyActions doesNotShow(HoversElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public HoversVerifyActions says(HoversElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public HoversVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public HoversVerifyActions holds(HoversElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public HoversVerifyActions isEmpty(HoversElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public HoversVerifyActions refusesEmpty(HoversElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public HoversVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, HoversElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
