// Generated by Suite Builder from a crawl of the site. Site navigation: the header and footer links.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Menus } from '../../../core/Menus';
import { SiteConfig } from '../../../core/SiteConfig';
import { StepLog } from '../../../core/StepLog';
import { UserActions } from '../../../core/UserActions';
import { UrlPaths } from '../../../uri/UrlPaths';
import { FooterElements } from '../../footer/FooterElements';
import { HeaderElements } from '../HeaderElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Navigation through the site's header and footer, from any page: somePage.navigateTo(). Each
 * method opens the link's dropdown when it is in one (Menus), clicks the link, and waits until the
 * page it leads to has fully loaded.
 */
export class HeaderNavigableActions {
  // Header

  // Footer

  // ==== YOURS (navigation): safe to edit; regenerating keeps what is between these lines ====
  // More ways around the site (a search box in the header, a language switch), e.g.:
  // search(words: string): SearchResultsPage {
  //   UserActions.type(HeaderElements.SEARCH_INPUT, words);
  //   UserActions.pressKey(HeaderElements.SEARCH_INPUT, 'Enter');
  //   return new SearchResultsPage().get();
  // }
  // ==== END YOURS (navigation) ====
}
