// Generated by Suite Builder from a crawl of the site. Checks for FloatingMenuPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.floatingmenu.actions;

import com.herokuapp.theinternet.tests.pages.floatingmenu.FloatingMenuPage;
import com.herokuapp.theinternet.tests.pages.floatingmenu.FloatingMenuElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on FloatingMenuPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class FloatingMenuVerifyActions {
    private final WebDriver driver;

    public FloatingMenuVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public FloatingMenuVerifyActions isLoaded() {
        FloatingMenuPage here = new FloatingMenuPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public FloatingMenuVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Floating Menu\")",
                FloatingMenuElements.FLOATING_MENU_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(FloatingMenuElements.SOME_HEADING)}. */
    public FloatingMenuVerifyActions shows(FloatingMenuElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public FloatingMenuVerifyActions doesNotShow(FloatingMenuElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public FloatingMenuVerifyActions says(FloatingMenuElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public FloatingMenuVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public FloatingMenuVerifyActions holds(FloatingMenuElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public FloatingMenuVerifyActions isEmpty(FloatingMenuElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public FloatingMenuVerifyActions refusesEmpty(FloatingMenuElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public FloatingMenuVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, FloatingMenuElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
