// Generated by Suite Builder from a crawl of the site. Checks for DisappearingElementsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.disappearingelements.actions;

import com.herokuapp.theinternet.tests.pages.disappearingelements.DisappearingElementsPage;
import com.herokuapp.theinternet.tests.pages.disappearingelements.DisappearingElementsElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on DisappearingElementsPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class DisappearingElementsVerifyActions {
    private final WebDriver driver;

    public DisappearingElementsVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public DisappearingElementsVerifyActions isLoaded() {
        DisappearingElementsPage here = new DisappearingElementsPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public DisappearingElementsVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Disappearing Elements\")",
                DisappearingElementsElements.DISAPPEARING_ELEMENTS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(DisappearingElementsElements.SOME_HEADING)}. */
    public DisappearingElementsVerifyActions shows(DisappearingElementsElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public DisappearingElementsVerifyActions doesNotShow(DisappearingElementsElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public DisappearingElementsVerifyActions says(DisappearingElementsElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public DisappearingElementsVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public DisappearingElementsVerifyActions holds(DisappearingElementsElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public DisappearingElementsVerifyActions isEmpty(DisappearingElementsElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public DisappearingElementsVerifyActions refusesEmpty(DisappearingElementsElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public DisappearingElementsVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, DisappearingElementsElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
