// Generated by Suite Builder from a crawl of the site. Checks for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.forgotpassword.actions;

import com.herokuapp.theinternet.tests.pages.forgotpassword.ForgotPasswordPage;
import com.herokuapp.theinternet.tests.pages.forgotpassword.ForgotPasswordElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on ForgotPasswordPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class ForgotPasswordVerifyActions {
    private final Page page;

    public ForgotPasswordVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public ForgotPasswordVerifyActions isLoaded() {
        ForgotPasswordPage here = new ForgotPasswordPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public ForgotPasswordVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Forgot Password\")",
                ForgotPasswordElements.FORGOT_PASSWORD_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(ForgotPasswordElements.SOME_HEADING)}. */
    public ForgotPasswordVerifyActions shows(ForgotPasswordElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public ForgotPasswordVerifyActions doesNotShow(ForgotPasswordElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public ForgotPasswordVerifyActions says(ForgotPasswordElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public ForgotPasswordVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public ForgotPasswordVerifyActions holds(ForgotPasswordElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public ForgotPasswordVerifyActions isEmpty(ForgotPasswordElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public ForgotPasswordVerifyActions refusesEmpty(ForgotPasswordElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public ForgotPasswordVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, ForgotPasswordElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
