// Generated by Suite Builder from a crawl of the site. Click actions for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.forgotpassword.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.forgotpassword.ForgotPasswordElements;
import com.herokuapp.theinternet.tests.pages.forgotpassword.ForgotPasswordPage;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on ForgotPasswordPage. Clicks that change page return the next page; others return this. */
public class ForgotPasswordClickActions {
    private final Page page;

    public ForgotPasswordClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the button "Retrieve password". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public ForgotPasswordPage retrievePassword() {
        UserActions.click(page, ForgotPasswordElements.RETRIEVE_PASSWORD_BUTTON);
        return new ForgotPasswordPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public ForgotPasswordVerifyActions verify() {
        return new ForgotPasswordVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public ForgotPasswordClickActions acceptTerms() {
    //     UserActions.click(page, ForgotPasswordElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
