// Generated by Suite Builder from a crawl of the site. EnterActions for InputsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { SiteConfig } from '../../../core/SiteConfig';
import { UserActions } from '../../../core/UserActions';
import { InputsElements } from '../InputsElements';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on InputsPage.
 * The crawl's own are below; add more (elements to InputsElements, then methods here) in the YOURS block.
 */
export class InputsEnterActions {
  /** Types into the number field "NUMBER_FIELD_INPUT". */
  numberField(text: string): InputsEnterActions {
    UserActions.type(InputsElements.NUMBER_FIELD_INPUT, text);
    return this;
  }

  /** Empties the number field "NUMBER_FIELD_INPUT". */
  clearNumberField(): InputsEnterActions {
    UserActions.clear(InputsElements.NUMBER_FIELD_INPUT);
    return this;
  }

  // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
  // One method per field, e.g.:
  // email(text: string): InputsEnterActions {
  //   UserActions.type(InputsElements.EMAIL_INPUT, text);
  //   return this;
  // }
  // A password or other secret: SiteConfig.secret('password').then((p) => UserActions.typeSecret(InputsElements.PASSWORD_INPUT, p));
  // A dropdown: UserActions.choose(InputsElements.COUNTRY_SELECT, country);
  // ==== END YOURS (actions) ====
}
