// Generated by Suite Builder from a crawl of the site. Page object for ChallengingDomPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { ChallengingDomElements } from './ChallengingDomElements';
import { ChallengingDomReadActions } from './actions/ChallengingDomReadActions';
import { ChallengingDomVerifyActions } from './actions/ChallengingDomVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /challenging_dom.
 * Stories call it:  "Challenging DOM" (the links that lead here).
 * Get here:         new ChallengingDomPage().open()
 *                   from HomePage: click().goToChallengingDom()
 * The crawl saw:    1 page of this type (/challenging_dom); it showed "Challenging DOM", "Lorem", "Ipsum", "Dolor", "Sit", "Amet".
 * Proven loaded by: the heading "Challenging DOM" and the heading "Lorem" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/challenging_dom.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/ChallengingDomPage/ and add what it shows to ChallengingDomElements.
 */
export class ChallengingDomPage extends LoadablePage<ChallengingDomPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default a4ba6fd7
  static readonly PROVES_LOADED: readonly PageElement[] = [
    ChallengingDomElements.CHALLENGING_DOM_HEADING,
    ChallengingDomElements.LOREM_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('ChallengingDomPage');
  }

  /** Goes to /challenging_dom and waits until it has fully loaded. */
  open(): ChallengingDomPage {
    this.navigate(UrlPaths.CHALLENGING_DOM);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.CHALLENGING_DOM, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.CHALLENGING_DOM}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(ChallengingDomPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${ChallengingDomPage.TITLE}"`);
    for (const element of ChallengingDomPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(ChallengingDomElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): ChallengingDomReadActions {
    return new ChallengingDomReadActions();
  }

  verify(): ChallengingDomVerifyActions {
    return new ChallengingDomVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
