// Generated by Suite Builder from a crawl of the site. Locators for ChallengingDomPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings } from '../../core/Headings';
import { byXPath, elements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /challenging_dom.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const ChallengingDomElements = elements({
  // Section headings the crawled pages of this type share. One a test does not use is harmless.
  /** Heading "Challenging DOM": every crawled page of this type showed it. */
  CHALLENGING_DOM_HEADING: Headings.named('Challenging DOM'),
  /** Heading "Lorem": every crawled page of this type showed it. */
  LOREM_HEADING: Headings.named('Lorem'),
  /** Heading "Ipsum": every crawled page of this type showed it. */
  IPSUM_HEADING: Headings.named('Ipsum'),
  /** Heading "Dolor": every crawled page of this type showed it. */
  DOLOR_HEADING: Headings.named('Dolor'),
  /** Heading "Sit": every crawled page of this type showed it. */
  SIT_HEADING: Headings.named('Sit'),
  /** Heading "Amet": every crawled page of this type showed it. */
  AMET_HEADING: Headings.named('Amet'),

  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
