// Generated by Suite Builder from a crawl of the site. Click actions for DynamicLoadingPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamicloading.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.dynamicloading.DynamicLoadingElements;
import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.DynamicLoadingDetailPage;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on DynamicLoadingPage. Clicks that change page return the next page; others return this. */
public class DynamicLoadingClickActions {
    private final Page page;

    public DynamicLoadingClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to DynamicLoadingDetailPage (e.g. Example 1: Element on page that is hidden) and waits for it. */
    public DynamicLoadingDetailPage goToDynamicLoadingDetail(String name) {
        UserActions.click(page, DynamicLoadingElements.getDynamicLoadingDetailLink(name));
        return new DynamicLoadingDetailPage(page).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public DynamicLoadingVerifyActions verify() {
        return new DynamicLoadingVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public DynamicLoadingClickActions acceptTerms() {
    //     UserActions.click(page, DynamicLoadingElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
