// Generated by Suite Builder from a crawl of the site. The site footer.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { byXPath, navElements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** The site footer: links on at least 80% of the crawled pages, with the path each leads to. */
export const FooterElements = navElements({
  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // More of it, as the path it leads to (or null) and its locator, e.g.:
  // SEARCH_BUTTON: { path: null, ...byCss("header button[aria-label='Search']") },
  // ==== END YOURS (elements) ====
});
