// Generated by Suite Builder from a crawl of the site. Checks for JqueryuiPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.jqueryui.actions;

import com.herokuapp.theinternet.tests.pages.jqueryui.JqueryuiPage;
import com.herokuapp.theinternet.tests.pages.jqueryui.JqueryuiElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on JqueryuiPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class JqueryuiVerifyActions {
    private final WebDriver driver;

    public JqueryuiVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public JqueryuiVerifyActions isLoaded() {
        JqueryuiPage here = new JqueryuiPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public JqueryuiVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"JQuery UI\")",
                JqueryuiElements.JQUERY_UI_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(JqueryuiElements.SOME_HEADING)}. */
    public JqueryuiVerifyActions shows(JqueryuiElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public JqueryuiVerifyActions doesNotShow(JqueryuiElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public JqueryuiVerifyActions says(JqueryuiElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public JqueryuiVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public JqueryuiVerifyActions holds(JqueryuiElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public JqueryuiVerifyActions isEmpty(JqueryuiElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public JqueryuiVerifyActions refusesEmpty(JqueryuiElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public JqueryuiVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, JqueryuiElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
