// Generated by Suite Builder from a crawl of the site. Click actions for JqueryuiPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.jqueryui.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.jqueryui.JqueryuiElements;
import com.herokuapp.theinternet.tests.pages.jqueryuimenu.JqueryuiMenuPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on JqueryuiPage. Clicks that change page return the next page; others return this. */
public class JqueryuiClickActions {
    private final WebDriver driver;

    public JqueryuiClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks the link to JqueryuiMenuPage (Menu) and waits for it. */
    public JqueryuiMenuPage goToJqueryuiMenu() {
        UserActions.click(driver, JqueryuiElements.JQUERYUI_MENU_LINK);
        return new JqueryuiMenuPage(driver).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public JqueryuiVerifyActions verify() {
        return new JqueryuiVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public JqueryuiClickActions acceptTerms() {
    //     UserActions.click(driver, JqueryuiElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
