// Generated by Suite Builder from a crawl of the site. Page object for CheckboxesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.checkboxes;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.CheckableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.checkboxes.actions.CheckboxesCheckActions;
import com.herokuapp.theinternet.tests.pages.checkboxes.actions.CheckboxesReadActions;
import com.herokuapp.theinternet.tests.pages.checkboxes.actions.CheckboxesVerifyActions;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /checkboxes.
 * Stories call it:  "Checkboxes" (the links that lead here).
 * Get here:         new CheckboxesPage(driver).open()
 *                   from HomePage: click().goToCheckboxes()
 * The crawl saw:    1 page of this type (/checkboxes); it showed "Checkboxes".
 * Proven loaded by: the heading "Checkboxes" (isLoaded(), PROVES_LOADED: what a copy edit leaves
 *                   alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/checkboxes.html (the page's HTML when crawled: check a locator
 *                   there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/CheckboxesPage/
 *                   (saved-pages/README.md) and add what it shows to CheckboxesElements.
 * </pre>
 */
public class CheckboxesPage extends LoadablePage<CheckboxesPage> implements
        CheckableAction<CheckboxesCheckActions>,
        ReadableAction<CheckboxesReadActions>,
        VerifiableAction<CheckboxesVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "The Internet";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default e7b4b39e
    static final List<CheckboxesElements> PROVES_LOADED = List.of(
            CheckboxesElements.CHECKBOXES_HEADING);
    // ==== END YOURS (load-proof) ====

    public CheckboxesPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to /checkboxes and waits until it has fully loaded. */
    public CheckboxesPage open() {
        navigate(UrlPaths.CHECKBOXES);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(driver, UrlPaths.CHECKBOXES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + UrlPaths.CHECKBOXES);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);

        if (!WaitActions.waitForTitle(driver, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + driver.getTitle() + "\", expected \"" + TITLE + "\"");
        }

        for (CheckboxesElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, CheckboxesElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public CheckboxesCheckActions check() {
        return new CheckboxesCheckActions(driver, true);
    }

    @Override
    public CheckboxesCheckActions uncheck() {
        return new CheckboxesCheckActions(driver, false);
    }

    @Override
    public CheckboxesReadActions read() {
        return new CheckboxesReadActions(driver);
    }

    @Override
    public CheckboxesVerifyActions verify() {
        return new CheckboxesVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
