// Generated by Suite Builder from a crawl of the site. Page object for DragAndDropPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.draganddrop;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.draganddrop.actions.DragAndDropReadActions;
import com.herokuapp.theinternet.tests.pages.draganddrop.actions.DragAndDropVerifyActions;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /drag_and_drop.
 * Stories call it:  "Drag and Drop" (the links that lead here).
 * Get here:         new DragAndDropPage(page).open()
 *                   from HomePage: click().goToDragAndDrop()
 * The crawl saw:    1 page of this type (/drag_and_drop); it showed "Drag and Drop".
 * Proven loaded by: the heading "Drag and Drop" (isLoaded(), PROVES_LOADED: what a copy edit leaves
 *                   alone first).
 * As crawled:       crawl/pages/drag_and_drop.html (the page's HTML when crawled: check a locator
 *                   there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/DragAndDropPage/
 *                   (saved-pages/README.md) and add what it shows to DragAndDropElements.
 * </pre>
 */
public class DragAndDropPage extends LoadablePage<DragAndDropPage> implements
        ReadableAction<DragAndDropReadActions>,
        VerifiableAction<DragAndDropVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "The Internet";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 4b5684c1
    static final List<DragAndDropElements> PROVES_LOADED = List.of(
            DragAndDropElements.DRAG_AND_DROP_HEADING);
    // ==== END YOURS (load-proof) ====

    public DragAndDropPage(Page page) {
        super(page);
    }

    /** Goes to /drag_and_drop and waits until it has fully loaded. */
    public DragAndDropPage open() {
        navigate(UrlPaths.DRAG_AND_DROP);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.DRAG_AND_DROP);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.DRAG_AND_DROP);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (DragAndDropElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, DragAndDropElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public DragAndDropReadActions read() {
        return new DragAndDropReadActions(page);
    }

    @Override
    public DragAndDropVerifyActions verify() {
        return new DragAndDropVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
