// Generated by Suite Builder from a crawl of the site. Checks for DynamicLoadingDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.actions;

import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.DynamicLoadingDetailPage;
import com.herokuapp.theinternet.tests.pages.dynamicloadingdetail.DynamicLoadingDetailElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on DynamicLoadingDetailPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class DynamicLoadingDetailVerifyActions {
    private final WebDriver driver;

    public DynamicLoadingDetailVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public DynamicLoadingDetailVerifyActions isLoaded() {
        DynamicLoadingDetailPage here = new DynamicLoadingDetailPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public DynamicLoadingDetailVerifyActions isThePageOf(String name) {
        Checks.isOnPath(driver, UrlPaths.dynamicLoadingDetail(name));
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public DynamicLoadingDetailVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Dynamically Loaded Page Elements\")",
                DynamicLoadingDetailElements.DYNAMICALLY_LOADED_PAGE_ELEMENTS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(DynamicLoadingDetailElements.SOME_HEADING)}. */
    public DynamicLoadingDetailVerifyActions shows(DynamicLoadingDetailElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public DynamicLoadingDetailVerifyActions doesNotShow(DynamicLoadingDetailElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public DynamicLoadingDetailVerifyActions says(DynamicLoadingDetailElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public DynamicLoadingDetailVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public DynamicLoadingDetailVerifyActions holds(DynamicLoadingDetailElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public DynamicLoadingDetailVerifyActions isEmpty(DynamicLoadingDetailElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public DynamicLoadingDetailVerifyActions refusesEmpty(DynamicLoadingDetailElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public DynamicLoadingDetailVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, DynamicLoadingDetailElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
