// Generated by Suite Builder from a crawl of the site. Checks for InputsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.inputs.actions;

import com.herokuapp.theinternet.tests.pages.inputs.InputsPage;
import com.herokuapp.theinternet.tests.pages.inputs.InputsElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on InputsPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class InputsVerifyActions {
    private final WebDriver driver;

    public InputsVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public InputsVerifyActions isLoaded() {
        InputsPage here = new InputsPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public InputsVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Inputs\")",
                InputsElements.INPUTS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(InputsElements.SOME_HEADING)}. */
    public InputsVerifyActions shows(InputsElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public InputsVerifyActions doesNotShow(InputsElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public InputsVerifyActions says(InputsElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public InputsVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public InputsVerifyActions holds(InputsElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public InputsVerifyActions isEmpty(InputsElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public InputsVerifyActions refusesEmpty(InputsElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public InputsVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, InputsElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
