// Generated by Suite Builder from a crawl of the site. Locators for DynamicControlsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { Headings } from '../../core/Headings';
import { byXPath, elements } from '../../core/PageElement';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /dynamic_controls.
 * Steps name each one by its label: SUBMIT_BUTTON is "the submit button".
 */
export const DynamicControlsElements = elements({
  // Section headings the crawled pages of this type share. One a test does not use is harmless.
  /** Heading "Dynamic Controls": every crawled page of this type showed it. */
  DYNAMIC_CONTROLS_HEADING: Headings.named('Dynamic Controls'),
  /** Heading "Remove/add": every crawled page of this type showed it. */
  REMOVE_ADD_HEADING: Headings.named('Remove/add'),
  /** Heading "Enable/disable": every crawled page of this type showed it. */
  ENABLE_DISABLE_HEADING: Headings.named('Enable/disable'),

  // "Remove/add" form (from the crawl: nothing was typed, clicked or sent).
  /** checkbox "CHECKBOX": seen by the crawl on /dynamic_controls. */
  CHECKBOX: byXPath('//div[@id=\'checkbox\']//input'),
  /** button "Remove": seen by the crawl on /dynamic_controls. */
  REMOVE_BUTTON: byXPath('//button[normalize-space()=\'Remove\']'),

  // "Enable/disable" form (from the crawl: nothing was typed, clicked or sent).
  /** text field "TEXT_FIELD_INPUT": seen by the crawl on /dynamic_controls. */
  TEXT_FIELD_INPUT: byXPath('//form[@id=\'input-example\']//input'),
  /** button "Enable": seen by the crawl on /dynamic_controls. */
  ENABLE_BUTTON: byXPath('//button[normalize-space()=\'Enable\']'),

  // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
  // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
  // paste straight in, e.g.:
  // SUBMIT_BUTTON: byXPath("//button[@data-testid='submit']"),
  // ==== END YOURS (elements) ====
});

// ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
// Locators that take a parameter (one row of a table, say), e.g.:
// export function getResultLink(name: string): PageElement {
//   return element('RESULT_LINK', byXPath(`//a[normalize-space()=${literal(name)}]`));
// }
// ==== END YOURS (extras) ====
