// Generated by Suite Builder from a crawl of the site. The "Enable/disable" form on DynamicControlsPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what DynamicControlsTasks.fillEnableDisableForm takes.
import { SiteConfig } from '../../core/SiteConfig';

/**
 * The "Enable/disable" form on DynamicControlsPage, as one value: its fields in page order, what
 * DynamicControlsTasks.fillEnableDisableForm types and chooses. Change one field with a spread:
 * `{ ...EnableDisable.sample(), textField: '...' }`.
 */
export interface EnableDisable {
  textField: string;
}

export const EnableDisable = {
  /** Values any copy of the site takes, each plausible for its field; one can be set for a run: npx cypress run --expose textField=... */
  sample(): EnableDisable {
    return {
      textField: SiteConfig.value('textField', 'Test textField'),
    };
  },
};
