// Generated by Suite Builder from a crawl of the site. Checks for TyposPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.typos.actions;

import com.herokuapp.theinternet.tests.pages.typos.TyposPage;
import com.herokuapp.theinternet.tests.pages.typos.TyposElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on TyposPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class TyposVerifyActions {
    private final WebDriver driver;

    public TyposVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public TyposVerifyActions isLoaded() {
        TyposPage here = new TyposPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public TyposVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Typos\")",
                TyposElements.TYPOS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(TyposElements.SOME_HEADING)}. */
    public TyposVerifyActions shows(TyposElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public TyposVerifyActions doesNotShow(TyposElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public TyposVerifyActions says(TyposElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public TyposVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public TyposVerifyActions holds(TyposElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public TyposVerifyActions isEmpty(TyposElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public TyposVerifyActions refusesEmpty(TyposElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public TyposVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, TyposElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
