// Generated by Suite Builder from a crawl of the site. Page object for StatusCodesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.statuscodesdetail;

import com.herokuapp.theinternet.tests.core.LoadablePage;
import com.herokuapp.theinternet.tests.core.WaitActions;
import com.herokuapp.theinternet.tests.core.actions.ClickableAction;
import com.herokuapp.theinternet.tests.core.actions.NavigableAction;
import com.herokuapp.theinternet.tests.core.actions.ReadableAction;
import com.herokuapp.theinternet.tests.core.actions.VerifiableAction;
import com.herokuapp.theinternet.tests.pages.header.actions.HeaderNavigableActions;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.actions.StatusCodesDetailClickActions;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.actions.StatusCodesDetailReadActions;
import com.herokuapp.theinternet.tests.pages.statuscodesdetail.actions.StatusCodesDetailVerifyActions;
import com.herokuapp.theinternet.tests.uri.UrlPaths;
import org.openqa.selenium.WebDriver;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 3 pages, like /status_codes/301,
 *                   /status_codes/200.
 * Get here:         new StatusCodesDetailPage(driver).open("301")
 *                   from StatusCodesPage: click().goToStatusCodesDetail("200")
 * The crawl saw:    2 pages of this type (/status_codes/301, /status_codes/200); every one showed
 *                   "Status Codes".
 * Proven loaded by: the heading "Status Codes" (isLoaded(), PROVES_LOADED: what a copy edit leaves
 *                   alone first).
 * As crawled:       crawl/pages/status_codes/301.html, crawl/pages/status_codes/200.html (the
 *                   page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/StatusCodesDetailPage/
 *                   (saved-pages/README.md) and add what it shows to StatusCodesDetailElements.
 * </pre>
 */
public class StatusCodesDetailPage extends LoadablePage<StatusCodesDetailPage> implements
        ClickableAction<StatusCodesDetailClickActions>,
        ReadableAction<StatusCodesDetailReadActions>,
        VerifiableAction<StatusCodesDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/status_codes/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 47290142
    public static final List<String> EXAMPLES = List.of(
            "301",
            "200");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 6a6febae
    static final List<StatusCodesDetailElements> PROVES_LOADED = List.of(
            StatusCodesDetailElements.STATUS_CODES_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public StatusCodesDetailPage(WebDriver driver) {
        super(driver);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public StatusCodesDetailPage open(String name) {
        expectedPath = UrlPaths.statusCodesDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(driver, expectedPath)
                : WaitActions.waitForUrlShape(driver, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + driver.getCurrentUrl() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(driver);


        for (StatusCodesDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(driver, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(driver, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(driver, StatusCodesDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public StatusCodesDetailClickActions click() {
        return new StatusCodesDetailClickActions(driver);
    }

    @Override
    public StatusCodesDetailReadActions read() {
        return new StatusCodesDetailReadActions(driver);
    }

    @Override
    public StatusCodesDetailVerifyActions verify() {
        return new StatusCodesDetailVerifyActions(driver);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(driver);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
