// Generated by Suite Builder from a crawl of the site. Click actions for WindowsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.windows.actions;

import com.herokuapp.theinternet.tests.core.StepLog;
import com.herokuapp.theinternet.tests.core.UserActions;
import com.herokuapp.theinternet.tests.pages.windows.WindowsElements;
import com.herokuapp.theinternet.tests.pages.windowsnew.WindowsNewPage;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on WindowsPage. Clicks that change page return the next page; others return this. */
public class WindowsClickActions {
    private final WebDriver driver;

    public WindowsClickActions(WebDriver driver) {
        this.driver = driver;
    }

    /** Clicks the link to WindowsNewPage (Click Here) and waits for it. It opens in a new tab. */
    public WindowsNewPage goToWindowsNew() {
        WebDriver tab = UserActions.clickOpeningNewTab(driver, WindowsElements.WINDOWS_NEW_LINK);
        return new WindowsNewPage(tab).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public WindowsVerifyActions verify() {
        return new WindowsVerifyActions(driver);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public WindowsClickActions acceptTerms() {
    //     UserActions.click(driver, WindowsElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
