// Generated by Suite Builder from a crawl of the site. Page object for DynamicContentPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { LoadablePage } from '../../core/LoadablePage';
import { type PageElement } from '../../core/PageElement';
import { WaitActions } from '../../core/WaitActions';
import { UrlPaths } from '../../uri/UrlPaths';
import { HeaderNavigableActions } from '../header/actions/HeaderNavigableActions';
import { DynamicContentElements } from './DynamicContentElements';
import { DynamicContentReadActions } from './actions/DynamicContentReadActions';
import { DynamicContentVerifyActions } from './actions/DynamicContentVerifyActions';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * What it is:       the page at /dynamic_content.
 * Stories call it:  "Dynamic Content" (the links that lead here).
 * Get here:         new DynamicContentPage().open()
 *                   from HomePage: click().goToDynamicContent()
 * The crawl saw:    1 page of this type (/dynamic_content); it showed "Dynamic Content".
 * Proven loaded by: the heading "Dynamic Content" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/dynamic_content.html (the page's HTML when crawled).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form does when sent. Save the page to saved-pages/DynamicContentPage/ and add what it shows to DynamicContentElements.
 */
export class DynamicContentPage extends LoadablePage<DynamicContentPage> {
  /** The title from the crawl. */
  static readonly TITLE = 'The Internet';

  /**
   * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
   * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
   * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
   */
  // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default edbaed80
  static readonly PROVES_LOADED: readonly PageElement[] = [
    DynamicContentElements.DYNAMIC_CONTENT_HEADING,
  ];
  // ==== END YOURS (load-proof) ====

  constructor() {
    super('DynamicContentPage');
  }

  /** Goes to /dynamic_content and waits until it has fully loaded. */
  open(): DynamicContentPage {
    this.navigate(UrlPaths.DYNAMIC_CONTENT);
    return this.get();
  }

  protected isLoaded(): void {
    WaitActions.forUrl(UrlPaths.DYNAMIC_CONTENT, (url) => `${this.name} did not load! URL was ${url}, expected ${UrlPaths.DYNAMIC_CONTENT}`);
    WaitActions.forPageLoad();
    WaitActions.forTitle(DynamicContentPage.TITLE, (title) => `${this.name} did not load! Title was "${title}", expected "${DynamicContentPage.TITLE}"`);
    for (const element of DynamicContentPage.PROVES_LOADED) {
      WaitActions.forVisibilityOf(element, `${this.name} did not load! ${element.name} was not visible!`);
    }
    WaitActions.noteIfStillLoading(this.name); // proven by address, title and checks: a late load event is named, not failed

    // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
    // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
    // WaitActions.forInvisibilityOf(DynamicContentElements.LOADING_SPINNER, `${this.name} did not load! LOADING_SPINNER never went away!`);
    // ==== END YOURS (load-checks) ====
  }

  read(): DynamicContentReadActions {
    return new DynamicContentReadActions();
  }

  verify(): DynamicContentVerifyActions {
    return new DynamicContentVerifyActions();
  }

  navigateTo(): HeaderNavigableActions {
    return new HeaderNavigableActions();
  }

  // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
  // ==== END YOURS (extras) ====
}
