// Generated by Suite Builder from a crawl of the site. The "Enable/disable" form on DynamicControlsPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what DynamicControlsTasks.fillEnableDisableForm takes.
package com.herokuapp.theinternet.tests.pages.dynamiccontrols;

import com.herokuapp.theinternet.tests.core.SiteConfig;

/**
 * The "Enable/disable" form on DynamicControlsPage, as one value: its fields in page order, what
 * {@link DynamicControlsTasks#fillEnableDisableForm(EnableDisable)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code EnableDisable.sample().withTextField("...")}.
 */
public record EnableDisable(String textField) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DtextField=...) or in suite.properties, by its name.
     */
    public static EnableDisable sample() {
        return new EnableDisable(
                SiteConfig.value("textField", "Test textField"));
    }

    /** This EnableDisable with textField in place of its own. */
    public EnableDisable withTextField(String textField) {
        return new EnableDisable(textField);
    }
}
