// Generated by Suite Builder from a crawl of the site. Tasks for ForgotPasswordPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
import { ForgotPassword } from './ForgotPassword';
import { ForgotPasswordPage } from './ForgotPasswordPage';
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on ForgotPasswordPage, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
export class ForgotPasswordTasks {
  /**
   * Fills the "forgot_password" form, field by field in page order, and stops before sending it: a generated
   * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds `.click().retrievePassword()`: what the site does then is not something the crawl saw.
   */
  fillForgotPasswordForm(form: ForgotPassword): ForgotPasswordPage;
  /** @deprecated Takes the form's record now (G-152): fillForgotPasswordForm(ForgotPassword.sample()). This one goes in a later release. */
  fillForgotPasswordForm(eMail: string): ForgotPasswordPage;
  fillForgotPasswordForm(...given: [ForgotPassword] | string[]): ForgotPasswordPage {
    const form: ForgotPassword = typeof given[0] === 'string' ? { eMail: given[0] as string } : (given[0] as ForgotPassword);
    const here = new ForgotPasswordPage();
    here.enter().eMail(form.eMail);
    return here;
  }

  // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
  // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
  // signUp(email: string): ThankYouPage {
  //   const here = new ForgotPasswordPage();
  //   here.enter().email(email);
  //   here.check().terms();
  //   return here.click().submit();
  // }
  // ==== END YOURS (tasks) ====
}
