// Generated by Suite Builder from a crawl of the site. Checks for TablesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package com.herokuapp.theinternet.tests.pages.tables.actions;

import com.herokuapp.theinternet.tests.pages.tables.TablesPage;
import com.herokuapp.theinternet.tests.pages.tables.TablesElements;
import com.herokuapp.theinternet.tests.core.Checks;
import com.herokuapp.theinternet.tests.core.StepLog;
import org.openqa.selenium.WebDriver;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on TablesPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class TablesVerifyActions {
    private final WebDriver driver;

    public TablesVerifyActions(WebDriver driver) {
        this.driver = driver;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public TablesVerifyActions isLoaded() {
        TablesPage here = new TablesPage(driver);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public TablesVerifyActions sectionHeadingsVisible() {
        Checks.allShown(driver, "its section headings (\"Data Tables\", \"Example 1\", \"Last Name\", \"First Name\", \"Email\", \"Due\")",
                TablesElements.DATA_TABLES_HEADING, TablesElements.EXAMPLE_1_HEADING, TablesElements.LAST_NAME_HEADING, TablesElements.FIRST_NAME_HEADING, TablesElements.EMAIL_HEADING, TablesElements.DUE_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(TablesElements.SOME_HEADING)}. */
    public TablesVerifyActions shows(TablesElements element) {
        Checks.isShown(driver, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public TablesVerifyActions doesNotShow(TablesElements element) {
        Checks.isNotShown(driver, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public TablesVerifyActions says(TablesElements element, String text) {
        Checks.hasText(driver, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public TablesVerifyActions showsText(String text) {
        Checks.pageShowsText(driver, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public TablesVerifyActions holds(TablesElements element, String text) {
        Checks.hasValue(driver, element, text);
        return this;
    }

    /** The field is empty. */
    public TablesVerifyActions isEmpty(TablesElements element) {
        Checks.hasValue(driver, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public TablesVerifyActions refusesEmpty(TablesElements element) {
        Checks.refusesEmpty(driver, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public TablesVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(driver, TablesElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
